'use strict';

// Specimen cards. Etymologies are real; where the standard account is disputed, the text says so.
// word: the specimen. origin: shown when the word is revealed. clue: crossword-style, letter count appended.
// cousins: etymological relatives, revealed at the end of the case.

module.exports = [
  // --- pharmacopoeia ---
  { cat: 'pharmacopoeia', word: 'assassin', origin: 'Arabic ḥashshāshīn, "hashish-eaters": the slur hostile chroniclers pinned on the Nizari Ismaili sect, whose agents killed political targets from mountain fortresses. Whether they actually used hashish is disputed. The slur outlived them.', clue: 'Hired killer with hashish in the name', cousins: ['hashish'] },
  { cat: 'pharmacopoeia', word: 'morphine', origin: 'Named in 1817 by the German pharmacist Sertürner after Morpheus, Greek god of dreams, for what it did to his test subjects. He was one of them.', clue: 'Opiate named for the god of dreams', cousins: ['morph', 'amorphous', 'metamorphosis'] },
  { cat: 'pharmacopoeia', word: 'heroin', origin: 'A Bayer trademark, 1898, from German heroisch, "heroic", for how it made patients feel. Marketed as a non-addictive cough remedy and a cure for morphine addiction.', clue: "Bayer's heroic cough medicine", cousins: ['hero', 'heroic'] },
  { cat: 'pharmacopoeia', word: 'nicotine', origin: 'From Jean Nicot, French ambassador to Portugal, who sent tobacco to the French court in 1560 as a medicine.', clue: 'Alkaloid named for a French ambassador', cousins: [] },
  { cat: 'pharmacopoeia', word: 'narcotic', origin: 'Greek narkē, "numbness, stupor". Narcolepsy is the same root; so, by one account, is narcissus, the flower whose scent was said to stupefy.', clue: 'Numbing drug, from the Greek for stupor', cousins: ['narcolepsy', 'narcissus', 'narcosis'] },
  { cat: 'pharmacopoeia', word: 'toxic', origin: 'Greek toxon, "bow". Toxikon pharmakon was the poison smeared on arrowheads. The bow was forgotten; the poison stayed.', clue: 'Poisonous, from the Greek for a bow', cousins: ['intoxicate', 'toxin', 'detox'] },
  { cat: 'pharmacopoeia', word: 'intoxicate', origin: 'Medieval Latin intoxicare, "to poison". Being drunk is, etymologically, being poisoned. The pleasant sense arrived in the 1500s.', clue: 'Poison yourself, pleasantly', cousins: ['toxic', 'toxin'] },
  { cat: 'pharmacopoeia', word: 'addict', origin: 'Latin addictus: in Roman law, a debtor handed over to a creditor as a bonded slave. To be addicted is to be legally awarded to something.', clue: 'Debtor handed over to a creditor, in Rome', cousins: ['dictate', 'dictionary', 'verdict', 'edict', 'predict'] },
  { cat: 'pharmacopoeia', word: 'alcohol', origin: 'Arabic al-kuḥl, the powdered antimony used as eyeliner. Alchemists stretched it to any fine powder or distilled essence; by the 1700s it meant the spirit of wine.', clue: 'Spirit that began as Arabic eyeliner', cousins: ['kohl'] },
  { cat: 'pharmacopoeia', word: 'sober', origin: 'Latin sobrius, from se- ("without") + ebrius ("drunk"). Inebriated is the same root going the other way.', clue: 'Not drunk, in Latin', cousins: ['inebriated'] },
  { cat: 'pharmacopoeia', word: 'ecstasy', origin: 'Greek ekstasis, "standing outside oneself". A displacement of the mind: first mystical, then chemical.', clue: 'Standing outside yourself, in Greek', cousins: ['static', 'stasis', 'stand'] },
  { cat: 'pharmacopoeia', word: 'opium', origin: 'Greek opion, "poppy juice", diminutive of opos, "sap".', clue: 'Poppy juice', cousins: ['opiate', 'opioid'] },
  { cat: 'pharmacopoeia', word: 'cocaine', origin: "From coca, the Andean leaf, via Quechua kuka, plus the chemists' -ine. Isolated 1860, named in English by 1874.", clue: 'Alkaloid from a Quechua leaf', cousins: ['coca'] },
  { cat: 'pharmacopoeia', word: 'cannabis', origin: 'Greek kannabis, borrowed from a Scythian or Thracian source. Canvas, once woven from hemp, is the same word wearing different clothes.', clue: 'Plant that gave its name to canvas', cousins: ['canvas', 'hemp'] },
  { cat: 'pharmacopoeia', word: 'junkie', origin: 'From junk, 1920s American slang for narcotics, itself from junk meaning old rope, then rubbish.', clue: 'Addict, from old rope', cousins: ['junk'] },
  { cat: 'pharmacopoeia', word: 'dope', origin: 'Dutch doop, "sauce, dipping". Thick liquids, then opium (smoked as a thick syrup), then any drug, then a fool.', clue: 'Drug word from a Dutch sauce', cousins: ['dip'] },
  { cat: 'pharmacopoeia', word: 'hangover', origin: 'Something that hangs over from the night before. First recorded in 1894 meaning a survival or leftover; medical by 1904.', clue: 'What survives the night before', cousins: ['hang', 'over'] },
  { cat: 'pharmacopoeia', word: 'pharmacy', origin: 'Greek pharmakon: drug, poison, or spell, depending on dose and intent. The Greeks did not distinguish; neither does the body.', clue: 'From a Greek word meaning both remedy and poison', cousins: ['pharmaceutical'] },
  { cat: 'pharmacopoeia', word: 'venom', origin: 'Latin venenum, originally a love potion or charm, from Venus. Then any potion. Then poison.', clue: 'Poison that began as a love potion', cousins: ['venus', 'venerate', 'venereal'] },
  { cat: 'pharmacopoeia', word: 'anesthesia', origin: 'Greek an- ("without") + aisthēsis ("sensation"). Oliver Wendell Holmes suggested the word in 1846 to the dentist who had just used ether on a patient.', clue: 'Without feeling', cousins: ['aesthetic', 'synesthesia'] },
  { cat: 'pharmacopoeia', word: 'whiskey', origin: 'Irish uisce beatha, "water of life". Latin aqua vitae, French eau-de-vie, Scandinavian akvavit: every culture told itself the same lie.', clue: 'Water of life, in Gaelic', cousins: ['water'] },
  { cat: 'pharmacopoeia', word: 'vodka', origin: 'Russian voda, "water", with a diminutive ending. Little water.', clue: 'Little water, in Russian', cousins: ['water'] },
  { cat: 'pharmacopoeia', word: 'coffee', origin: 'Arabic qahwa, which may originally have meant wine, via Turkish kahve. The Ottoman coffeehouse was periodically banned as a den of sedition.', clue: 'Arabic wine that became a morning drink', cousins: ['café', 'cafeteria'] },

  // --- the mind, failing ---
  { cat: 'mind', word: 'paranoia', origin: 'Greek para ("beside") + nous ("mind"). A mind that has slipped to one side.', clue: "Beside one's mind", cousins: ['paranormal', 'parallel', 'parasite'] },
  { cat: 'mind', word: 'hysteria', origin: 'Greek hystera, "womb". For two thousand years the diagnosis assumed the patient had one.', clue: 'Wandering-womb diagnosis', cousins: ['hysterectomy'] },
  { cat: 'mind', word: 'melancholy', origin: 'Greek melas ("black") + kholē ("bile"). Humoral medicine blamed sadness on an excess of black bile, and prescribed purging.', clue: 'Sadness from black bile', cousins: ['melanin', 'melanoma', 'cholera', 'choleric'] },
  { cat: 'mind', word: 'nostalgia', origin: 'Coined in 1688 by a Swiss medical student from Greek nostos ("homecoming") + algos ("pain"), to name a disease killing Swiss mercenaries posted abroad. Treatment: send them home.', clue: 'Homesickness, once a fatal diagnosis', cousins: ['analgesic', 'neuralgia'] },
  { cat: 'mind', word: 'lunatic', origin: 'Latin luna, "moon". Madness was thought to wax and wane with the phases.', clue: 'Mad by moonlight', cousins: ['lunar'] },
  { cat: 'mind', word: 'lobotomy', origin: 'Greek lobos ("lobe") + tomē ("a cutting"). Its inventor received the Nobel Prize in Medicine in 1949.', clue: 'Nobel-winning brain cut', cousins: ['anatomy', 'atom', 'tome', 'epitome'] },
  { cat: 'mind', word: 'idiot', origin: 'Greek idiōtēs, a private person: one who took no part in public life. The Athenians thought that was contemptible. The insult followed.', clue: 'Private citizen, in Athens', cousins: ['idiom', 'idiosyncrasy'] },
  { cat: 'mind', word: 'moron', origin: 'Greek mōros, "dull, foolish". Adopted in 1910 by the psychologist Henry Goddard as a clinical grade of intelligence, one step above imbecile.', clue: 'Clinical grade from 1910, now just an insult', cousins: ['oxymoron', 'sophomore'] },
  { cat: 'mind', word: 'cretin', origin: 'Swiss French crestin, "Christian", applied to people with congenital hypothyroidism in Alpine valleys. The point was that they were still human. The word forgot the point.', clue: 'Slur that began by insisting on humanity', cousins: ['christian'] },
  { cat: 'mind', word: 'stupid', origin: 'Latin stupere, "to be stunned, struck senseless". Stupendous is the same root: something that stuns.', clue: 'Stunned senseless', cousins: ['stupor', 'stupendous'] },
  { cat: 'mind', word: 'fanatic', origin: 'Latin fanaticus, "of a temple", frenzied by a god. Fan, the sports kind, is its clipped American descendant.', clue: 'Temple-mad', cousins: ['profane', 'fan'] },
  { cat: 'mind', word: 'enthusiasm', origin: 'Greek enthousiasmos, "possessed by a god": en + theos. In the 1600s it was an accusation.', clue: 'Divine possession, now mere keenness', cousins: ['theology', 'atheist', 'pantheon'] },
  { cat: 'mind', word: 'panic', origin: 'From Pan, the goat-legged god, whose shout was said to scatter armies in the night.', clue: 'Terror from a goat god', cousins: [] },
  { cat: 'mind', word: 'nightmare', origin: "The mare was a demon that sat on a sleeper's chest and crushed the breath out. No horse was ever involved.", clue: 'Chest-sitting demon, not a horse', cousins: [] },
  { cat: 'mind', word: 'genius', origin: 'Latin genius: the guardian spirit assigned to each person at birth. It became a talent, then a person with one.', clue: 'Guardian spirit turned IQ score', cousins: ['genie', 'gene', 'genre', 'gender', 'generate'] },

  // --- the body, failing ---
  { cat: 'body', word: 'cadaver', origin: 'Latin cadaver, from cadere, "to fall". A corpse is one who has fallen. Casualty, decadent and accident are the same fall.', clue: 'Body that has fallen, in Latin', cousins: ['cadence', 'decadent', 'accident', 'casualty'] },
  { cat: 'body', word: 'sarcasm', origin: 'Greek sarkazein, "to tear flesh", from sarx, "flesh".', clue: 'Wit that strips flesh', cousins: ['sarcophagus', 'sarcoma'] },
  { cat: 'body', word: 'sarcophagus', origin: 'Greek sarkophagos, "flesh-eating". A limestone quarried near Assos was believed to consume a corpse within weeks, so coffins were made from it.', clue: 'Flesh-eating stone coffin', cousins: ['sarcasm', 'sarcoma', 'esophagus'] },
  { cat: 'body', word: 'euthanasia', origin: 'Greek eu ("good") + thanatos ("death"). For centuries it meant only dying well; the doctor with the syringe is a nineteenth-century addition.', clue: 'A good death, in Greek', cousins: ['euphemism', 'eulogy', 'thanatology'] },
  { cat: 'body', word: 'cemetery', origin: 'Greek koimētērion, "sleeping place". Early Christians preferred it to the pagan necropolis, "city of the dead". Same residents.', clue: 'Sleeping place, euphemistically', cousins: ['coma'] },
  { cat: 'body', word: 'macabre', origin: 'From the French danse macabre, the medieval dance of death. Probably from the Maccabees, whose martyrdoms were a popular subject for the dance.', clue: 'Gruesome, from a dance of death', cousins: [] },
  { cat: 'body', word: 'ghoul', origin: 'Arabic ghūl, a desert demon that robs graves and eats the dead. Entered English through a translation of the Arabian Nights in 1786.', clue: 'Grave-robbing demon from Arabic', cousins: [] },
  { cat: 'body', word: 'zombie', origin: 'Haitian Creole zonbi, from West African languages (Kikongo nzambi, "god", or zumbi, "fetish"). A body reanimated and enslaved by a sorcerer, which is to say, a labour metaphor.', clue: 'Reanimated corpse, via Haiti', cousins: [] },
  { cat: 'body', word: 'nausea', origin: 'Greek nausia, "seasickness", from naus, "ship". The word left the ship; the feeling did not.', clue: 'Seasickness, before it left the ship', cousins: ['nautical', 'navy', 'astronaut'] },
  { cat: 'body', word: 'muscle', origin: 'Latin musculus, "little mouse", for the way a flexed bicep moves under the skin. Mussel is the same word.', clue: 'Little mouse under the skin', cousins: ['mussel', 'mouse'] },
  { cat: 'body', word: 'quarantine', origin: 'Italian quaranta giorni, "forty days": how long plague-era Venice held ships offshore before letting anyone ashore.', clue: 'Forty days in the harbour', cousins: ['quart', 'quarter'] },
  { cat: 'body', word: 'malaria', origin: 'Italian mala aria, "bad air". The swamp air took the blame for centuries before the mosquito did.', clue: 'Bad-air fever', cousins: ['malice', 'malady', 'aria', 'air'] },
  { cat: 'body', word: 'vaccine', origin: "Latin vacca, \"cow\". Jenner scratched cowpox into a boy's arm in 1796 and the cow has been in the word ever since.", clue: 'Shot that comes from a cow', cousins: ['vaquero', 'buckaroo'] },
  { cat: 'body', word: 'pupil', origin: "Latin pupilla, \"little doll\": the tiny reflection of yourself you see in someone else's eye.", clue: 'Eye part, or a little doll', cousins: ['puppet', 'puppy'] },
  { cat: 'body', word: 'tremendous', origin: 'Latin tremendus, "to be trembled at". Huge enough to make you shake.', clue: 'Huge enough to make you tremble', cousins: ['tremble', 'tremor'] },

  // --- sex, mostly by accident ---
  { cat: 'sex', word: 'orchid', origin: 'Greek orkhis, "testicle", for the shape of the paired root tubers. Botanists have never been subtle.', clue: 'Flower named for testicles', cousins: [] },
  { cat: 'sex', word: 'avocado', origin: 'Nahuatl āhuacatl, which also meant testicle. Spanish reshaped it toward abogado, "lawyer", which is not an improvement.', clue: 'Fruit that meant testicle in Nahuatl', cousins: ['guacamole'] },
  { cat: 'sex', word: 'pencil', origin: "Latin penicillus, \"little tail\", a painter's fine brush: the diminutive of penis, \"tail\". Penicillin is the brush-shaped mould.", clue: 'Writing tool that is a little tail', cousins: ['penicillin', 'penis'] },
  { cat: 'sex', word: 'vanilla', origin: 'Spanish vainilla, "little pod", diminutive of vaina, "sheath", from Latin vagina. The plainest flavour has the least plain name.', clue: 'Flavour named for a little sheath', cousins: ['vagina'] },
  { cat: 'sex', word: 'porcelain', origin: "Italian porcellana, the cowrie shell, from porcella, \"little sow\": the shell's opening was compared to a sow's vulva. Fine china got the shell's sheen and its name.", clue: 'Fine china named for a little sow', cousins: ['pork', 'porcupine', 'porpoise'] },
  { cat: 'sex', word: 'musk', origin: "Sanskrit muṣka, \"testicle\", for the shape of the deer's scent gland.", clue: 'Perfume from a Sanskrit testicle', cousins: [] },
  { cat: 'sex', word: 'seminar', origin: 'Latin seminarium, "seed-bed", from semen, "seed". A seminary is the same bed.', clue: 'Seed-bed for graduate students', cousins: ['semen', 'seminary', 'disseminate'] },
  { cat: 'sex', word: 'testify', origin: 'Latin testis, "witness". The story that Romans swore on their testicles is folk etymology; the anatomical word is a later metaphor, a witness to virility.', clue: 'Bear witness', cousins: ['testament', 'contest', 'protest', 'testicle'] },
  { cat: 'sex', word: 'pornography', origin: 'Greek pornē ("prostitute") + graphein ("to write"). The English word dates from the 1850s, coined to describe the frescoes of Pompeii.', clue: 'Writing about prostitutes, in Greek', cousins: ['graphic', 'photograph'] },
  { cat: 'sex', word: 'fornicate', origin: 'Latin fornix, "arch, vault". Roman brothels operated in vaulted cellars under the arches.', clue: 'Sin under a Roman arch', cousins: [] },
  { cat: 'sex', word: 'lewd', origin: 'Old English lǣwede, "lay, not clergy". Then unlettered, then vulgar, then lustful. The clergy wrote the dictionary.', clue: "Once just meant 'not a priest'", cousins: [] },
  { cat: 'sex', word: 'punk', origin: "In Shakespeare's day, a prostitute. By 1900, a young hoodlum. By 1976, a genre.", clue: 'Elizabethan prostitute, now a genre', cousins: [] },
  { cat: 'sex', word: 'harlot', origin: 'Old French herlot, a vagabond or rogue. Applied to men for three centuries before it settled on women.', clue: 'Rogue that changed sex', cousins: [] },
  { cat: 'sex', word: 'bastard', origin: 'Old French bastard, perhaps from bast, a packsaddle: a child conceived on a packsaddle rather than in a marriage bed. One account among several.', clue: 'Packsaddle child, by one account', cousins: [] },
  { cat: 'sex', word: 'obscene', origin: 'Latin obscenus, "ill-omened, filthy". The theatre story that it means "offstage" is not supported by anything.', clue: 'Ill-omened, then filthy', cousins: [] },
  { cat: 'sex', word: 'profane', origin: 'Latin pro fano, "in front of the temple", meaning outside it. Whatever was not consecrated.', clue: 'Outside the temple', cousins: ['fanatic'] },

  // --- insults and reversals ---
  { cat: 'insults', word: 'villain', origin: "Latin villanus, a farmhand attached to a villa. The aristocracy's word for a peasant became everyone's word for a criminal.", clue: 'Farmhand turned evildoer', cousins: ['villa', 'village'] },
  { cat: 'insults', word: 'nice', origin: 'Latin nescius, "ignorant". It meant foolish, then timid, then fussy, then fine, then pleasant. It has never once meant anything firmly.', clue: 'Pleasant word that spent centuries meaning stupid', cousins: ['science', 'omniscient', 'conscience'] },
  { cat: 'insults', word: 'silly', origin: 'Old English sǣlig, "blessed, happy". Blessed became innocent, innocent became harmless, harmless became feeble, feeble became foolish.', clue: 'Foolish, from blessed', cousins: [] },
  { cat: 'insults', word: 'awful', origin: 'Full of awe. It once meant inspiring reverence; awesome came from the same word and went the other way.', clue: 'Awe-inspiring, gone bad', cousins: ['awe', 'awesome'] },
  { cat: 'insults', word: 'sinister', origin: 'Latin sinister, "left". The left side was unlucky in Roman augury, and left-handers have been paying for it since.', clue: 'Evil, from the left hand', cousins: [] },
  { cat: 'insults', word: 'sardonic', origin: 'From Sardinia. A Sardinian plant was said to cause facial convulsions resembling grim laughter, followed by death.', clue: 'Grimly mocking, like a Sardinian poison', cousins: [] },
  { cat: 'insults', word: 'glamour', origin: 'A Scots mangling of grammar. Book-learning was suspected of being magic; a glamour was a spell cast over the eyes.', clue: 'Grammar that became a spell', cousins: ['grammar', 'grimoire'] },
  { cat: 'insults', word: 'disaster', origin: 'Italian disastro, from dis- + astro, "star". Ill-starred.', clue: 'Calamity written in the stars', cousins: ['astronomy', 'asterisk', 'astral'] },
  { cat: 'insults', word: 'hazard', origin: 'Arabic az-zahr, "the dice", through Old French hasard, a dice game. Risk was a game before it was a warning.', clue: 'Danger that was a dice game', cousins: [] },
  { cat: 'insults', word: 'apocalypse', origin: 'Greek apokalypsis, "an uncovering". Not the end of the world: the moment the cover comes off.', clue: 'Uncovering, not ending', cousins: ['calypso', 'eucalyptus'] },
  { cat: 'insults', word: 'catastrophe', origin: "Greek katastrophē, \"overturning\": the final turn of a drama's plot.", clue: 'The overturning at the end of a play', cousins: ['strophe', 'apostrophe'] },
  { cat: 'insults', word: 'tragedy', origin: 'Greek tragōidia, "goat song", from tragos + ōidē. Nobody is sure why the goat.', clue: 'Goat song', cousins: ['ode', 'melody', 'parody', 'comedy'] },
  { cat: 'insults', word: 'pandemonium', origin: 'Milton, 1667: Pandæmonium, the capital of Hell. "All demons."', clue: "Milton's capital of Hell", cousins: ['demon', 'pandemic', 'pantheon', 'panorama'] },
  { cat: 'insults', word: 'grotesque', origin: "Italian grottesca, from grotta: the bizarre painted figures found in the buried rooms of Nero's palace, which excavators took for caves.", clue: "Cave art from Nero's buried palace", cousins: ['grotto', 'crypt'] },
  { cat: 'insults', word: 'crypt', origin: 'Greek kryptē, "hidden". Cryptography hides words; the crypt hides everything else.', clue: 'Hidden place under the church', cousins: ['cryptic', 'cryptography', 'grotto'] },
  { cat: 'insults', word: 'bizarre', origin: 'French, from Italian bizzarro, "angry, hot-headed". The Basque bizar ("beard") is often claimed and never proven.', clue: 'Strange, from the Italian for angry', cousins: [] },

  // --- money, work, and the state ---
  { cat: 'money', word: 'deadline', origin: 'In Civil War prison camps, a line beyond which prisoners were shot. Newspapers softened it to a time limit in the 1920s.', clue: 'Line that got prisoners shot', cousins: ['dead', 'line'] },
  { cat: 'money', word: 'freelance', origin: 'A medieval mercenary whose lance was free for hire. Coined by Walter Scott in Ivanhoe, 1819. The gig economy is older than the gig.', clue: 'Mercenary with a lance for hire', cousins: ['lance'] },
  { cat: 'money', word: 'mortgage', origin: 'Old French mort gage, "dead pledge". Dead either because the debt dies when paid, or because the property does when it is not.', clue: 'Dead pledge', cousins: ['mortal', 'mortuary', 'engage', 'wage'] },
  { cat: 'money', word: 'bankrupt', origin: 'Italian banca rotta, "broken bench". A moneylender who failed had his bench smashed in the market.', clue: 'Broke, from a broken bench', cousins: ['bank', 'bench', 'rupture', 'corrupt'] },
  { cat: 'money', word: 'boycott', origin: 'Captain Charles Boycott, an Irish land agent whose tenants, servants and shopkeepers all refused to deal with him in 1880.', clue: 'Refusal named for an ostracised land agent', cousins: [] },
  { cat: 'money', word: 'sabotage', origin: 'French sabot, a wooden clog. The story about workers throwing clogs into machinery is doubtful; the word meant clumsy, clog-footed work first.', clue: 'Wreckage with a wooden shoe in its past', cousins: [] },
  { cat: 'money', word: 'decimate', origin: 'Latin decimare: a Roman punishment that executed one soldier in ten from a mutinous unit. The nine survivors did the killing.', clue: 'Kill one in ten', cousins: ['decimal', 'december', 'dime', 'tithe'] },
  { cat: 'money', word: 'candidate', origin: 'Latin candidatus, "clothed in white", for the chalk-whitened toga Roman office-seekers wore. Candid is the same whiteness.', clue: 'Office-seeker in bleached white', cousins: ['candid', 'candle', 'incandescent'] },
  { cat: 'money', word: 'ambition', origin: 'Latin ambitio, "going around": canvassing the streets for votes. The Romans considered it faintly disgraceful.', clue: 'Going around begging for votes', cousins: ['ambient'] },
  { cat: 'money', word: 'gerrymander', origin: 'Governor Elbridge Gerry of Massachusetts plus salamander, for the shape of a district his party drew in 1812.', clue: "Rig districts like a governor's salamander", cousins: ['salamander'] },
  { cat: 'money', word: 'robot', origin: "Czech robota, \"forced labour\", from Karel Čapek's 1920 play R.U.R. The robots revolt. They always do.", clue: 'Machine born of forced labour', cousins: [] },
  { cat: 'money', word: 'scapegoat', origin: "Tyndale's 1530 coinage translating Leviticus: the goat that escapes into the desert carrying everyone's sins.", clue: 'Goat that carries the sins away', cousins: ['escape'] },
  { cat: 'money', word: 'checkmate', origin: 'Persian shāh māt, "the king is helpless" (or, by folk etymology, dead). Chess, check and exchequer all descend from the shah.', clue: 'The king is helpless, in Persian', cousins: ['check', 'chess', 'exchequer', 'shah'] },
  { cat: 'money', word: 'curfew', origin: 'Old French couvre-feu, "cover fire": the evening bell ordering hearths banked so the town would not burn down in its sleep.', clue: 'Evening order to cover the fire', cousins: ['cover'] },

  // --- learning ---
  { cat: 'learning', word: 'trivia', origin: 'Latin trivium, "three roads", where common people met and gossiped. Also the three lower liberal arts. Either way, beneath notice.', clue: 'Facts from a three-way crossroads', cousins: ['trivial'] },
  { cat: 'learning', word: 'calculate', origin: 'Latin calculus, "pebble", used on a counting board. Kidney stones and integral calculus share the pebble.', clue: 'Reckon with pebbles', cousins: ['calcium', 'chalk', 'calculus'] },
  { cat: 'learning', word: 'algorithm', origin: 'From al-Khwārizmī, the ninth-century Persian mathematician. His book on solving equations gave us algebra as well.', clue: 'Procedure named for a Persian mathematician', cousins: ['algebra'] },
  { cat: 'learning', word: 'school', origin: 'Greek scholē, "leisure": what free men did with time they did not have to sell. The word has reversed.', clue: 'Place of learning, from the Greek for leisure', cousins: ['scholar'] },
  { cat: 'learning', word: 'symposium', origin: "Greek symposion, \"drinking together\". Plato's was a wine party that turned into philosophy. The academic kind rarely goes the other way.", clue: 'Academic meeting that was a drinking party', cousins: ['potion', 'potable'] },
  { cat: 'learning', word: 'museum', origin: 'Greek mouseion, a seat of the Muses. The first famous one, at Alexandria, was a research institute, not a display case.', clue: 'Home of the Muses', cousins: ['music', 'muse', 'mosaic'] },
  { cat: 'learning', word: 'economy', origin: 'Greek oikonomia, "household management". It scaled up.', clue: 'Household management, at national scale', cousins: ['ecology', 'ecumenical'] },
  { cat: 'learning', word: 'clue', origin: 'A clew was a ball of thread. Theseus followed one out of the labyrinth, and the word has meant a way out of a puzzle since.', clue: 'Hint that was a ball of thread', cousins: ['clew'] },
  { cat: 'learning', word: 'zero', origin: 'Arabic ṣifr, "empty", via Italian zefiro. Cipher is the same word: nothing, and a code for hiding something.', clue: 'Empty, in Arabic', cousins: ['cipher'] },
  { cat: 'learning', word: 'planet', origin: 'Greek planētēs, "wanderer": the lights that would not stay put among the fixed stars.', clue: 'Wandering star', cousins: [] },
  { cat: 'learning', word: 'galaxy', origin: 'Greek galaxias, "milky". The same milk as lactose, and as lettuce, named for its sap.', clue: 'Star system that is Greek for milky', cousins: ['lactose', 'lettuce'] },
  { cat: 'learning', word: 'hermetic', origin: 'From Hermes Trismegistus, the legendary alchemist. An airtight seal was one of the secrets attributed to him.', clue: 'Airtight, thanks to a legendary alchemist', cousins: ['hermes'] },
  { cat: 'learning', word: 'serendipity', origin: 'Horace Walpole, 1754, from a fairy tale about the three princes of Serendip (Sri Lanka), who kept discovering things they were not looking for.', clue: 'Happy accident from three princes of Sri Lanka', cousins: [] },

  // --- things that lost or gained a letter ---
  { cat: 'letters', word: 'orange', origin: 'Sanskrit nāraṅga, via Persian and Arabic. English once said "a norange"; the N slid across to the article.', clue: 'Fruit that lost its N to an article', cousins: [] },
  { cat: 'letters', word: 'apron', origin: 'Old French naperon, "small tablecloth". "A napron" became "an apron". Napkin kept its N.', clue: 'Kitchen garb that also lost its N', cousins: ['napkin', 'napery'] },
  { cat: 'letters', word: 'nickname', origin: '"An ekename", an additional name, from eke, "also". The N migrated the other way.', clue: 'Extra name that gained an N', cousins: ['eke'] },
  { cat: 'letters', word: 'umpire', origin: 'Old French nonper, "not equal": the odd man brought in to settle a dispute between two. "A noumpere" lost its N.', clue: 'Referee who was once a non-peer', cousins: ['peer', 'pair', 'par'] },

  // --- animals, plants, weather ---
  { cat: 'nature', word: 'dandelion', origin: "French dent de lion, \"lion's tooth\", for the jagged leaf.", clue: "Lion's-tooth weed", cousins: ['dental', 'dentist'] },
  { cat: 'nature', word: 'daisy', origin: "Old English dæges ēage, \"day's eye\": it opens at dawn and closes at dusk.", clue: "The day's eye", cousins: ['day', 'eye'] },
  { cat: 'nature', word: 'window', origin: 'Old Norse vindauga, "wind-eye". A hole for the wind before it was a hole for the glass.', clue: 'Wind-eye, in Old Norse', cousins: ['wind', 'eye'] },
  { cat: 'nature', word: 'tulip', origin: 'Turkish tülbent, "turban", for the shape of the flower. The 1637 Dutch crash was in these.', clue: 'Flower shaped like a turban', cousins: ['turban'] },
  { cat: 'nature', word: 'walrus', origin: 'Dutch walrus, probably "whale-horse" with the halves swapped.', clue: 'Tusked whale-horse', cousins: ['whale', 'horse'] },
  { cat: 'nature', word: 'cobalt', origin: 'German Kobold, a mine goblin blamed for ore that looked like silver, yielded none, and poisoned the smelters with arsenic.', clue: 'Blue metal blamed on a goblin', cousins: [] },
  { cat: 'nature', word: 'nickel', origin: 'German Kupfernickel, "copper demon": ore that looked like copper and gave none.', clue: 'Copper demon', cousins: [] },
  { cat: 'nature', word: 'meander', origin: 'The Maeander, a river in Turkey famous in antiquity for never going anywhere directly.', clue: 'Wander like a Turkish river', cousins: [] },

  // --- gods and heroes ---
  { cat: 'gods', word: 'tantalize', origin: 'Tantalus, punished in Hades with fruit and water forever just out of reach.', clue: 'Tease like a king in Hades', cousins: ['tantalum'] },
  { cat: 'gods', word: 'atlas', origin: 'The Titan condemned to hold up the sky. Mercator put him on the cover of a book of maps in 1595 and the name stuck to the book.', clue: 'Book of maps named for a sky-bearing Titan', cousins: [] },
  { cat: 'gods', word: 'echo', origin: 'A nymph cursed to repeat only the last words spoken to her. She wasted away to a voice.', clue: 'Repeated sound, once a nymph', cousins: [] },
  { cat: 'gods', word: 'narcissism', origin: 'Narcissus fell in love with his reflection and starved beside it. Freud borrowed him in 1914.', clue: 'Self-love from a pond-gazer', cousins: ['narcotic'] },
  { cat: 'gods', word: 'mentor', origin: 'Mentor, the old friend Odysseus left in charge of his son. Athena borrowed his shape to do the actual mentoring.', clue: 'Guide from the Odyssey', cousins: [] },

  // --- food, clothes, the house ---
  { cat: 'food', word: 'companion', origin: 'Latin com- + panis: one you break bread with. Company is the same loaf.', clue: 'Bread-sharer, literally', cousins: ['company', 'pantry'] },
  { cat: 'food', word: 'journey', origin: "Old French journée, a day's travel. Journal, adjourn and sojourn are the same day.", clue: "A day's travel, extended", cousins: ['journal', 'adjourn', 'sojourn'] },
  { cat: 'food', word: 'carnival', origin: 'Latin carne vale, "farewell to meat", or carnem levare, "remove meat": the last feast before Lent.', clue: 'Festival that says goodbye to meat', cousins: ['carnivore', 'carnation', 'incarnate'] },
  { cat: 'food', word: 'infant', origin: 'Latin infans, "unable to speak". Infantry are foot soldiers too young to be knights.', clue: 'Baby who cannot yet speak, literally', cousins: ['infantry', 'fable', 'fate', 'fame'] },
  { cat: 'food', word: 'sugar', origin: 'Sanskrit śarkarā, "gravel, grit", via Persian and Arabic. Saccharine is the same grit.', clue: 'Sweetener from the Sanskrit for gravel', cousins: ['saccharine'] },
  { cat: 'food', word: 'candy', origin: 'Arabic qandī, "sugared", from Sanskrit khaṇḍa, "piece, fragment".', clue: 'Sweets with Sanskrit roots', cousins: [] },
  { cat: 'food', word: 'magazine', origin: 'Arabic makhāzin, "storehouses". A store of gunpowder, then a store of information.', clue: 'Periodical that was a storehouse', cousins: [] },
  { cat: 'food', word: 'sofa', origin: 'Arabic ṣuffa, a raised bench or ledge with cushions.', clue: 'Couch from an Arabic bench', cousins: [] },
  { cat: 'food', word: 'kiosk', origin: 'Turkish köşk, a garden pavilion, from Persian. It shrank.', clue: 'Small booth from a Turkish pavilion', cousins: [] },
  { cat: 'food', word: 'pajamas', origin: 'Persian pāy-jāma, "leg garment", via Hindi. Colonial officers brought the trousers home and kept them for bed.', clue: 'Nightwear that is a leg garment in Persian', cousins: [] },
  { cat: 'food', word: 'shampoo', origin: 'Hindi chāmpo, "press, knead": a massage, before it was a bottle.', clue: 'Hair wash that was a massage', cousins: [] },
  { cat: 'food', word: 'bungalow', origin: 'Hindi banglā, "in the Bengal style": a one-storey house with a veranda.', clue: 'One-storey house in the Bengal style', cousins: ['bengal'] },
  { cat: 'food', word: 'denim', origin: 'Serge de Nîmes, cloth from the French city. Jeans are from Genoa. Both were cheap and both were foreign.', clue: 'Jeans cloth from a French city', cousins: [] },
  { cat: 'food', word: 'ketchup', origin: 'Hokkien kê-tsiap, a fermented fish sauce. The tomato arrived two centuries later.', clue: 'Condiment descended from a fish sauce', cousins: [] },
  { cat: 'food', word: 'admiral', origin: 'Arabic amīr, "commander", as in amīr al-baḥr, commander of the sea. The D wandered in from Latin admirabilis.', clue: 'Naval chief from an Arabic commander', cousins: ['emir'] },
  { cat: 'food', word: 'tariff', origin: 'Arabic taʿrīf, "notification, list of fees", via Italian.', clue: 'Import tax from an Arabic notification', cousins: [] },
  { cat: 'food', word: 'hooligan', origin: 'Probably from Houlihan, an Irish surname, popularised by 1890s London newspapers and music-hall songs about a rowdy family.', clue: 'Rowdy from an Irish surname', cousins: [] },
].concat(require('./cards-science'), require('./cards-more'));
