'use strict';
// Two false origin stories per word, for the "why is it called that" mode. Each is written to sound
// like the true entries in families.js; none of them is true.
module.exports = {
  salt: ['Old English sealt, from a word for the white crust left on a shield after a sea crossing.', 'Latin saltare, "to leap", from the way it jumps in a hot pan.'],
  hospital: ['Latin hospes, "bed", the same root as horizontal. A place for lying down.', 'Greek hosios, "holy". The first ones were run by monks and the name kept the smell of incense.'],
  capital: ['Latin capere, "to seize". Capital was what you had seized in a war, and later what you had in a bank.', 'From Capitoline, the Roman hill where the treasury stood. Money was kept up there.'],
  genius: ['Latin gignere, "to know". A genius was one who knew.', 'Arabic jinn, a spirit of smoke, by way of the Crusaders. Genie is the same word.'],
  pedal: ['Latin pedere, "to break wind". A pedal was the bellows-plate of an organ.', 'Greek paidion, "little child": the lowest thing you could work with your foot.'],
  dictate: ['Latin digitus, "finger". To dictate was to point.', 'Latin dictus, "a decree of the dictator", who alone could speak without a vote.'],
  spirit: ['Latin spira, "coil": the coiling smoke of a sacrifice was the visible spirit.', 'Greek speirein, "to sow". The spirit was the seed that outlived the plant.'],
  company: ['Latin com- + pagus, "district". People from the same village who marched together.', 'Old French compagne, "countryside". A company was originally a country walk.'],
  vision: ['Latin vis, "force". The eye was thought to send out a force that touched things.', 'Old English wisan, "to know", cognate with wise: vision was foreknowledge before it was eyesight.'],
  manual: ['Latin manere, "to stay". A manual was the book that stayed by the machine.', 'Latin mane, "morning". Manual work was the work done at first light.'],
  legal: ['Latin legare, "to bind", from ligature. Law was what tied you.', 'From the Lex Julia, the first written Roman code; "legal" meant "of the Lex".'],
  grave: ['Latin gravare, "to bury". The two graves are one word after all.', 'Old French greve, "sand". Serious matters were written in the sand of the forum.'],
  mortal: ['Latin mortarium, "a bowl for grinding". Mortal things are the ones that get ground down.', 'Latin mora, "delay". A mortal was one who was only delayed.'],
  testament: ['Latin testis, "testicle". Romans swore oaths with a hand on them; hence testify and testament.', 'Latin tessera, "tile": a will was scratched on a roof tile.'],
  cardiac: ['Latin carduus, "thistle". The heart was drawn as a thistle head in early anatomy.', 'Greek kardia, "cabbage", for its shape once opened.'],
  lunatic: ['Latin lumen, "light". A lunatic saw a light no one else saw.', 'From Lunacy, a Roman prison on the Tiber where the mad were kept.'],
  pharmacy: ['Greek pharos, "lighthouse". The Alexandrian drug-sellers kept shop beneath it.', 'Latin farina, "flour". The first pharmacists were millers who ground herbs.'],
  toxic: ['Greek toxos, "yew", the tree whose berries poison.', 'Latin toxa, "the yolk of a rotten egg".'],
  narcotic: ['Greek narkissos, the flower, whose scent was said to bring sleep.', 'Latin narcus, "the north wind", which numbs.'],
  stupid: ['Latin stupa, "coarse flax"; a stupid person had a head of tow.', 'Latin stare + putare, "to stand and think" too long.'],
  terror: ['Latin terra, "earth". Terror was the fear of the earth shaking.', 'Greek teras, "monster". A terror was a monster before it was a feeling.'],
  sanity: ['Latin sanctus, "holy". The sane were those the gods had not touched.', 'Latin sanguis, "blood". Sanity was good blood.'],
  chemistry: ['Greek khymos, "juice". Chemistry was the study of juices.', 'Hebrew kemi, "blackened", from the soot of the furnace.'],
  physics: ['Greek phyllon, "leaf". Physics began as the study of plants.', 'Latin fixus, "fixed". The fixed laws, against the changing ones of politics.'],
  medicine: ['Latin medius, "middle". The healer stood between the sick and the dead.', 'From the Medici of Florence, who paid for the first medical schools.'],
  neuron: ['Greek neos, "new". A neuron was a new fibre found under the microscope.', 'Latin nervus, "knot", from the knots in a rope.'],
  psyche: ['Greek psykhros, "cold". The soul was the cold that left the body at death.', 'Greek psithyros, "whisper". The soul was the voice you heard alone.'],
  philosophy: ['Greek phyle, "tribe". Philosophy was the tribal knowledge of the wise.', 'Greek philos + sophos, "wise friend": a philosopher was your wise friend.'],
  logic: ['Greek logos, "to lie down". Logic was the argument that laid an opponent flat.', 'Latin locus, "place". Logic put each thing in its place.'],
  hypnosis: ['Greek hypo, "under", and nous, "mind". Below the mind.', 'Named for Hypnos, a Swiss mesmerist of the 1840s. The god was named after him.'],
  euphoria: ['Greek euphorbia, a milky weed that was smoked for pleasure.', 'Greek eu + phora, "good theft". The pleasant feeling of getting away with it.'],
  anxiety: ['Latin anxia, "the ankle". The anxious pace on their toes.', 'Greek anaxios, "unworthy". The feeling of not deserving it.'],
  trauma: ['Greek trauma, "dream". A trauma was a dream you could not wake from.', 'Latin trabs, "beam", from the injuries of builders.'],
  addict: ['Latin ad + dicere, "to say yes". An addict was one who always said yes.', 'Latin addere, "to add". An addict kept adding a little more.'],
  sober: ['Latin sub + ebur, "under ivory", pale as a tusk after a bad night.', 'Old English sober, "sombre". The sober were the sad.'],
  ecstasy: ['Greek ekstasis, "out of the stomach". A joy felt in the gut.', 'Greek ex + tasis, "stretched out", as a body on a rack.'],
  cannabis: ['Latin canis, "dog", after the smell of the burning leaf.', 'Greek kanna + bios, "reed life", the plant that lives like a reed.'],
  opium: ['Greek ops, "eye". Opium was first sold as an eye ointment.', 'Latin opus, "work". The workers\' drug.'],
  venom: ['Latin vena, "vein". Venom was what ran in the vein of a snake.', 'Latin ventus, "wind". Venom was the poison breath of a serpent.'],
  hangover: ['Old Norse hangr, "a dizzy spell", surviving in dialect until the 1800s.', 'From hanging over a rail on a ship: sailors\' slang for seasickness on land.'],
  sarcasm: ['Greek sarkos, "lizard". A sarcastic remark had a lizard\'s tongue.', 'Latin sarcire, "to mend". Sarcasm was the joke that stitched a wound shut.'],
  cadaver: ['Latin caro data vermibus, "flesh given to worms".', 'Latin cadus, "wine jar". A body laid out was as still as a full jar.'],
  euthanasia: ['Greek euthys, "straight". A straight death.', 'Greek eu + nasos, "a good nose": the physician judged by smell when it was time.'],
  crypt: ['Latin crux, "cross". A crypt was the space beneath the cross of the church.', 'Greek kryos, "cold". The cold room.'],
  panic: ['Greek pan, "all". Panic is the fear that seizes everyone at once.', 'Latin panis, "bread". Bread riots were the first panics.'],
  atlas: ['Arabic atlas, "smooth", a silk used to bind the first map books.', 'Latin ad + latus, "beside", a book kept at your side.'],
  nemesis: ['Greek nema, "thread", the thread the Fates cut.', 'Latin ne + mensis, "no month": the debt that could not be put off.'],
  cynic: ['Greek kyanos, "blue". The Cynics wore blue cloaks.', 'Greek kynikos, from Cynosarges, the school where Antisthenes taught. Nothing to do with dogs.'],
  stoic: ['Greek stoikhos, "row, line". The Stoics stood in ranks.', 'Greek stoutos, "sturdy". The sturdy ones.'],
  agnostic: ['Greek agnos, "lamb". One who is innocent of the matter.', 'Latin agnoscere, "to acknowledge". One who acknowledges only what is proved.'],
  nihilism: ['Latin nihil, "nothing", from Nihil, the personification of the void in Roman hymns.', 'Russian nichevo, "nothing", from the 1860s radicals who answered every question with it.'],
  paradox: ['Greek para + doxa, "beside the glory". A truth that stands beside the obvious one.', 'Latin parare + docere, "to prepare to teach". A paradox was a teacher\'s trick.'],
  nirvana: ['Sanskrit nir + vana, "no forest". The clearing at the end of the path.', 'Pali nibbana, "the cool", from the coolness after fever.'],
  oxygen: ['Greek oxys, "quick". The quick gas, the one that made things burn faster.', 'Named by Priestley for Oxford, where he isolated it.'],
  energy: ['Greek en + argos, "in silver". The shine in the metal.', 'Greek energeia, "in anger". The force of a temper.'],
  gravity: ['Latin gravare, "to bury". Things fall because the earth wants them buried.', 'Latin gravis, "pregnant". The heaviness of the earth.'],
  thug: ['Old English thugan, "to press". A thug pressed you.', 'Hindi thugna, "to strangle", the Thuggee method.'],
  cop: ['An acronym: Constable On Patrol.', 'From copper buttons on the first Metropolitan Police coats, 1829.'],
  muscle: ['Latin mus, "must", the strength you must use.', 'Greek mykes, "mushroom", from the shape of a flexed arm.'],
  disaster: ['Latin dis + aster, "without a flower": a field that failed.', 'Old French desastre, "the master is away", a ship with no captain.'],
  calculate: ['Latin calx, "heel". Roman merchants counted by tapping a heel.', 'Arabic al-qalqala, "the shaking", from shaking counting beads.'],
  rival: ['Latin rivalis, "the one who arrives", a latecomer who wants your place.', 'Old French rivel, "a rebel"; the b softened.'],
  vaccine: ['Latin vacuus, "empty": a vaccine is a hollow, harmless version of the disease.', 'From Vaccinium, the blueberry, whose juice was the first carrier.'],
  bank: ['Old English banc, "hill": the riverbank, and money piled up like earth.', 'Latin bancus, "a chain", the chained strongbox of the moneylender.'],
  malaria: ['Malay malar, "swamp", brought back by Dutch traders.', 'Greek malakos, "soft", from the softening of the spleen.'],
  pupil: ['Latin pupillus, "the little pope", the boy who led church responses.', 'Greek pyle, "gate": the pupil is the gate of the eye.'],
  window: ['Old English wind + dow, "a gift of wind".', 'Latin vinea, "vine": a lattice opening grown over with vines.'],
  candidate: ['Latin candere, "to be counted", from the tallying of votes.', 'From Candia, the Venetian name for Crete, where officers were elected.'],
  quarantine: ['Italian quarantia, the council of forty that governed Venice.', 'Latin quaerere, "to ask": the questioning of arriving sailors.'],
  trivial: ['Latin tribus, "tribe". Tribal matters were small matters.', 'Greek tribein, "to rub": worn smooth by use, hence commonplace.'],
  whiskey: ['Gaelic uisge, "mist", the vapour in the still.', 'Old Norse viska, "wisdom", the drink that loosens the tongue.'],
  clue: ['Old French clou, "nail": the nail that held the case together.', 'Latin claudere, "to close": the clue is what closes the case.'],
  nice: ['Latin nitidus, "shining, neat".', 'From Nice, the French resort, whose weather was famously pleasant.'],
  alarm: ['Latin ad + larma, "to the tears".', 'Arabic al-arm, "the drum", from the drum beaten in a raid.'],
  daisy: ['Old English dæsig, "dizzy", for the way the flower nods.', 'Latin dies + sinus, "the fold of the day", a flower that closes at night.'],
};
