'use strict';
// Two false origin stories per word, for the "why is it called that" mode. Each is written to sound
// like the true entries in families.js; none of them is true.
module.exports = {
  salt: ['Old English sealt, from a word for the white crust left on a shield after a sea crossing.', 'Latin saltare, "to leap", from the way it jumps in a hot pan.'],
  hospital: ['Latin hospes, "bed", the same root as horizontal. A place for lying down.', 'Greek hosios, "holy". The first ones were run by monks and the name kept the smell of incense.'],
  capital: ['Latin capere, "to seize". Capital was what you had seized in a war, and later what you had in a bank.', 'From Capitoline, the Roman hill where the treasury stood. Money was kept up there.'],
  genius: ['Latin gignere, "to know". A genius was one who knew.', 'Arabic jinn, a spirit of smoke, by way of the Crusaders. Genie is the same word.'],
  pedal: ['Latin pedere, "to break wind". A pedal was the bellows-plate of an organ.', 'Greek paidion, "little child": the lowest thing you could work with your foot.'],
  dictate: ['Latin digitus, "finger". To dictate was to point.', 'Latin dictus, "a decree of the dictator", who alone could speak without a vote.'],
  spirit: ['Latin spira, "coil": the coiling smoke of a sacrifice was the visible spirit.', 'Greek speirein, "to sow". The spirit was the seed that outlived the plant.'],
  company: ['Latin com- + pagus, "district". People from the same village who marched together.', 'Old French compagne, "countryside". A company was originally a country walk.'],
  vision: ['Latin vis, "force". The eye was thought to send out a force that touched things.', 'Old English wisan, "to know", cognate with wise: vision was foreknowledge before it was eyesight.'],
  manual: ['Latin manere, "to stay". A manual was the book that stayed by the machine.', 'Latin mane, "morning". Manual work was the work done at first light.'],
  legal: ['Latin legare, "to bind", from ligature. Law was what tied you.', 'From the Lex Julia, the first written Roman code; "legal" meant "of the Lex".'],
  grave: ['Latin gravare, "to bury". The two graves are one word after all.', 'Old French greve, "sand". Serious matters were written in the sand of the forum.'],
  mortal: ['Latin mortarium, "a bowl for grinding". Mortal things are the ones that get ground down.', 'Latin mora, "delay". A mortal was one who was only delayed.'],
  testament: ['Latin testis, "testicle". Romans swore oaths with a hand on them; hence testify and testament.', 'Latin tessera, "tile": a will was scratched on a roof tile.'],
  cardiac: ['Latin carduus, "thistle". The heart was drawn as a thistle head in early anatomy.', 'Greek kardia, "cabbage", for its shape once opened.'],
  lunatic: ['Latin lumen, "light". A lunatic saw a light no one else saw.', 'From Lunacy, a Roman prison on the Tiber where the mad were kept.'],
  pharmacy: ['Greek pharos, "lighthouse". The Alexandrian drug-sellers kept shop beneath it.', 'Latin farina, "flour". The first pharmacists were millers who ground herbs.'],
  toxic: ['Greek toxos, "yew", the tree whose berries poison.', 'Latin toxa, "the yolk of a rotten egg".'],
  narcotic: ['Greek narkissos, the flower, whose scent was said to bring sleep.', 'Latin narcus, "the north wind", which numbs.'],
  stupid: ['Latin stupa, "coarse flax"; a stupid person had a head of tow.', 'Latin stare + putare, "to stand and think" too long.'],
  terror: ['Latin terra, "earth". Terror was the fear of the earth shaking.', 'Greek teras, "monster". A terror was a monster before it was a feeling.'],
  sanity: ['Latin sanctus, "holy". The sane were those the gods had not touched.', 'Latin sanguis, "blood". Sanity was good blood.'],
  chemistry: ['Greek khymos, "juice". Chemistry was the study of juices.', 'Hebrew kemi, "blackened", from the soot of the furnace.'],
  physics: ['Greek phyllon, "leaf". Physics began as the study of plants.', 'Latin fixus, "fixed". The fixed laws, against the changing ones of politics.'],
  medicine: ['Latin medius, "middle". The healer stood between the sick and the dead.', 'From the Medici of Florence, who paid for the first medical schools.'],
  neuron: ['Greek neos, "new". A neuron was a new fibre found under the microscope.', 'Latin nervus, "knot", from the knots in a rope.'],
  psyche: ['Greek psykhros, "cold". The soul was the cold that left the body at death.', 'Greek psithyros, "whisper". The soul was the voice you heard alone.'],
  philosophy: ['Greek phyle, "tribe". Philosophy was the tribal knowledge of the wise.', 'Greek philos + sophos, "wise friend": a philosopher was your wise friend.'],
  logic: ['Greek logos, "to lie down". Logic was the argument that laid an opponent flat.', 'Latin locus, "place". Logic put each thing in its place.'],
  hypnosis: ['Greek hypo, "under", and nous, "mind". Below the mind.', 'Named for Hypnos, a Swiss mesmerist of the 1840s. The god was named after him.'],
  euphoria: ['Greek euphorbia, a milky weed that was smoked for pleasure.', 'Greek eu + phora, "good theft". The pleasant feeling of getting away with it.'],
  anxiety: ['Latin anxia, "the ankle". The anxious pace on their toes.', 'Greek anaxios, "unworthy". The feeling of not deserving it.'],
  trauma: ['Greek trauma, "dream". A trauma was a dream you could not wake from.', 'Latin trabs, "beam", from the injuries of builders.'],
  addict: ['Latin ad + dicere, "to say yes". An addict was one who always said yes.', 'Latin addere, "to add". An addict kept adding a little more.'],
  sober: ['Latin sub + ebur, "under ivory", pale as a tusk after a bad night.', 'Old English sober, "sombre". The sober were the sad.'],
  ecstasy: ['Greek ekstasis, "out of the stomach". A joy felt in the gut.', 'Greek ex + tasis, "stretched out", as a body on a rack.'],
  cannabis: ['Latin canis, "dog", after the smell of the burning leaf.', 'Greek kanna + bios, "reed life", the plant that lives like a reed.'],
  opium: ['Greek ops, "eye". Opium was first sold as an eye ointment.', 'Latin opus, "work". The workers\' drug.'],
  venom: ['Latin vena, "vein". Venom was what ran in the vein of a snake.', 'Latin ventus, "wind". Venom was the poison breath of a serpent.'],
  hangover: ['Old Norse hangr, "a dizzy spell", surviving in dialect until the 1800s.', 'From hanging over a rail on a ship: sailors\' slang for seasickness on land.'],
  sarcasm: ['Greek sarkos, "lizard". A sarcastic remark had a lizard\'s tongue.', 'Latin sarcire, "to mend". Sarcasm was the joke that stitched a wound shut.'],
  cadaver: ['Latin caro data vermibus, "flesh given to worms".', 'Latin cadus, "wine jar". A body laid out was as still as a full jar.'],
  euthanasia: ['Greek euthys, "straight". A straight death.', 'Greek eu + nasos, "a good nose": the physician judged by smell when it was time.'],
  crypt: ['Latin crux, "cross". A crypt was the space beneath the cross of the church.', 'Greek kryos, "cold". The cold room.'],
  panic: ['Greek pan, "all". Panic is the fear that seizes everyone at once.', 'Latin panis, "bread". Bread riots were the first panics.'],
  atlas: ['Arabic atlas, "smooth", a silk used to bind the first map books.', 'Latin ad + latus, "beside", a book kept at your side.'],
  nemesis: ['Greek nema, "thread", the thread the Fates cut.', 'Latin ne + mensis, "no month": the debt that could not be put off.'],
  cynic: ['Greek kyanos, "blue". The Cynics wore blue cloaks.', 'Greek kynikos, from Cynosarges, the school where Antisthenes taught. Nothing to do with dogs.'],
  stoic: ['Greek stoikhos, "row, line". The Stoics stood in ranks.', 'Greek stoutos, "sturdy". The sturdy ones.'],
  agnostic: ['Greek agnos, "lamb". One who is innocent of the matter.', 'Latin agnoscere, "to acknowledge". One who acknowledges only what is proved.'],
  nihilism: ['Latin nihil, "nothing", from Nihil, the personification of the void in Roman hymns.', 'Russian nichevo, "nothing", from the 1860s radicals who answered every question with it.'],
  paradox: ['Greek para + doxa, "beside the glory". A truth that stands beside the obvious one.', 'Latin parare + docere, "to prepare to teach". A paradox was a teacher\'s trick.'],
  nirvana: ['Sanskrit nir + vana, "no forest". The clearing at the end of the path.', 'Pali nibbana, "the cool", from the coolness after fever.'],
  oxygen: ['Greek oxys, "quick". The quick gas, the one that made things burn faster.', 'Named by Priestley for Oxford, where he isolated it.'],
  energy: ['Greek en + argos, "in silver". The shine in the metal.', 'Greek energeia, "in anger". The force of a temper.'],
  gravity: ['Latin gravare, "to bury". Things fall because the earth wants them buried.', 'Latin gravis, "pregnant". The heaviness of the earth.'],
  thug: ['Old English thugan, "to press". A thug pressed you.', 'Hindi thugna, "to strangle", the Thuggee method.'],
  cop: ['An acronym: Constable On Patrol.', 'From copper buttons on the first Metropolitan Police coats, 1829.'],
  muscle: ['Latin mus, "must", the strength you must use.', 'Greek mykes, "mushroom", from the shape of a flexed arm.'],
  disaster: ['Latin dis + aster, "without a flower": a field that failed.', 'Old French desastre, "the master is away", a ship with no captain.'],
  calculate: ['Latin calx, "heel". Roman merchants counted by tapping a heel.', 'Arabic al-qalqala, "the shaking", from shaking counting beads.'],
  rival: ['Latin rivalis, "the one who arrives", a latecomer who wants your place.', 'Old French rivel, "a rebel"; the b softened.'],
  vaccine: ['Latin vacuus, "empty": a vaccine is a hollow, harmless version of the disease.', 'From Vaccinium, the blueberry, whose juice was the first carrier.'],
  bank: ['Old English banc, "hill": the riverbank, and money piled up like earth.', 'Latin bancus, "a chain", the chained strongbox of the moneylender.'],
  malaria: ['Malay malar, "swamp", brought back by Dutch traders.', 'Greek malakos, "soft", from the softening of the spleen.'],
  pupil: ['Latin pupillus, "the little pope", the boy who led church responses.', 'Greek pyle, "gate": the pupil is the gate of the eye.'],
  window: ['Old English wind + dow, "a gift of wind".', 'Latin vinea, "vine": a lattice opening grown over with vines.'],
  candidate: ['Latin candere, "to be counted", from the tallying of votes.', 'From Candia, the Venetian name for Crete, where officers were elected.'],
  quarantine: ['Italian quarantia, the council of forty that governed Venice.', 'Latin quaerere, "to ask": the questioning of arriving sailors.'],
  trivial: ['Latin tribus, "tribe". Tribal matters were small matters.', 'Greek tribein, "to rub": worn smooth by use, hence commonplace.'],
  whiskey: ['Gaelic uisge, "mist", the vapour in the still.', 'Old Norse viska, "wisdom", the drink that loosens the tongue.'],
  clue: ['Old French clou, "nail": the nail that held the case together.', 'Latin claudere, "to close": the clue is what closes the case.'],
  nice: ['Latin nitidus, "shining, neat".', 'From Nice, the French resort, whose weather was famously pleasant.'],
  alarm: ['Latin ad + larma, "to the tears".', 'Arabic al-arm, "the drum", from the drum beaten in a raid.'],
  daisy: ['Old English dæsig, "dizzy", for the way the flower nods.', 'Latin dies + sinus, "the fold of the day", a flower that closes at night.'],
  salary: ['Latin salire, "to leap": pay handed over the counter, a sum that jumps from one hand to another.', 'From the Salii, the leaping priests of Mars, who were the first Romans paid a fixed stipend from the treasury.'],
  sabotage: ['French sabre + tage: the damage a cavalry sabre does to a loom, from the Lyons silk riots.', 'Arabic sabat, "Saturday", the day Ottoman dockworkers refused to work.'],
  sincere: ['Latin sine cera, "without wax": honest sculptors did not hide flaws with wax, so their work was sincere.', 'Latin sinus + cor, "the fold of the heart", where a Roman kept what he truly thought.'],
  gossip: ['Old English gos + sipe, "goose-talk", from the cackling of a flock.', 'Old French gosse, "a lad", and the boys who carried news between manors.'],
  ketchup: ['Cantonese kwai chap, "eggplant sauce", from the purple original.', 'From the Ketch family of Boston, who bottled the first tomato sauce for sale in 1810.'],
  avocado: ['Spanish abogado, "lawyer", because the fruit was a fee the Aztec courts accepted.', 'Portuguese aveia + cado, "fallen oat", from the texture of the flesh.'],
  robot: ['Greek rhobos, "a whirring", the sound of a mechanical toy.', 'From R.O.B.O.T., a 1920 Prague trade fair acronym for Rotating Operated Body Of Tin.'],
  nightmare: ['Old English niht + mearh, "night horse": the demon rode you like a horse.', 'Old Norse nattmara, "night mother", the ghost of a woman who died in childbirth.'],
  lord: ['Old English lar + ord, "the point of teaching", the man who instructed the household.', 'Old Norse lodr, "the fire-keeper", who owned the hearth.'],
  mortgage: ['Old French mort + gage, "dead wage", the rent you stop receiving on land you have pledged.', 'Latin mortarium, the trough the deed was ceremonially mixed in with lime.'],
  tantalize: ['Greek tantalos, "a swaying", from the way a heavy branch bobs out of reach.', 'From Tantalus, an Athenian innkeeper famous for showing dishes he never served.'],
  mercury: ['Latin merx, "a thief", because the metal steals into every crack.', 'Greek merkos, "the running one", a name given by Alexandrian alchemists.'],
  gangster: ['Dutch gang, "corridor", from the alleyway gangs of Amsterdam docks.', 'From the Gang of Four, a New York Tammany faction of the 1850s, by way of newspaper shorthand.'],
  hoodlum: ['A San Francisco reporter reversed the name of gang leader Muldoon and got "noodlum", which a typesetter read as hoodlum.', 'Cantonese hui dung lam, "the bad boys of the alley", from Chinatown, 1870.'],
  jury: ['Latin iuvenis, "young men", the twelve youths who judged games in Rome.', 'Old French jour, "day": the men summoned for a day of hearing.'],
  fiasco: ['Italian fiasco, "a flash": a firework that fails to go off.', 'From the opera Fiasco, which closed in Milan after one night in 1782.'],
  alcohol: ['Arabic al-ghul, "the demon", the spirit that takes possession of the drinker.', 'Latin alcoholium, "a cooling", from the chill of evaporating spirit on the skin.'],
  nicotine: ['Greek nikē + teinein, "victory-stretching", for how a smoker draws breath.', 'From Nicotia, the Ottoman port where Venetians first bought tobacco.'],
  caffeine: ['Arabic kaf, "the palm of the hand", the way beans were measured out.', 'From Kaffee-Ihn, the Leipzig coffee house where it was first isolated.'],
  psychedelic: ['Greek psyche + delos, "soul of the island", from the trance rites of Delos.', 'Coined by Timothy Leary in 1963 from psyche + delicious.'],
  morphine: ['Greek morphē + inē, "the shaping of sleep", named by Sertürner for what it did to his dreams.', 'From Morpheus, the Latin name of a Dutch chemist, Morfius, who first sold it.'],
  heroin: ['German Heer + Ohne, "army without", a name for a painkiller that let soldiers fight wounded.', 'Named for Hero of Alexandria, whose engine was compared to the drug\'s effect on the heart.'],
  cocaine: ['Nahuatl cacahuatl, the same plant as cocoa, before botanists separated them.', 'Spanish coca, "a cook", the leaf being brewed rather than chewed.'],
  tequila: ['Nahuatl te-quilla, "stone that cries", from the volcanic rock the agave grows on.', 'From Don Pedro Tequila, who was granted the first distilling licence in 1795.'],
  absinthe: ['Greek a- + psinthos, "undrinkable", a warning that became a name.', 'From the Absinthe brothers of Neuchâtel, who bottled it in 1797.'],
  delirium: ['Latin de + lira, "off the lyre", a string out of tune.', 'Latin delere, "to destroy": the mind erasing itself.'],
  paranoia: ['Greek para + noia, "beside the boat": a sailor gone overboard.', 'Greek paranous, "the false mind", a term for a stage villain.'],
  melancholy: ['Greek melos + kholē, "song of anger", the lament of a wronged man.', 'Latin mel + collum, "honey at the throat", a sweetness that will not go down.'],
  hysteria: ['Greek hysteros, "later": a delayed reaction to a shock.', 'Latin histrio, "an actor", for the theatrical fits.'],
  phobia: ['Greek phōs + bia, "light-force", the flinch from a sudden brightness.', 'From Phoebe, the Titan, whose name was invoked against fear.'],
  idiot: ['Greek idein + otos, "one who sees with the ears", a simpleton.', 'Latin idem + otium, "the same leisure": a man who never changed.'],
  nostalgia: ['Latin nostra + algia, "our pain", the ache for one\'s own people.', 'Greek nostos + algos, coined by Homer for Odysseus.'],
  oblivion: ['Latin ob + livor, "against the bruise", the fading of a mark.', 'Latin oblivio, from oliva: the smoothness of oil poured over a wax tablet.'],
  enthusiasm: ['Greek en + thysia, "in sacrifice", the fervour of the altar.', 'Greek enthous, "inside the seat", the excitement of a spectator.'],
  quantum: ['Latin quantus, from quando, "when": the smallest unit of time.', 'Coined by Einstein from German Quant, "a pinch".'],
  atom: ['Greek atmos, "vapour": the smallest visible particle in steam.', 'Greek a- + tomos, "without a book", a thing too small to write about.'],
  virus: ['Latin vir, "man": a disease that passes from man to man.', 'Greek iōs, "an arrow", the poison that flies.'],
  planet: ['Greek plane, "flat", the disk of a wandering star.', 'Latin planta, "a sole": the stars that walked.'],
  galaxy: ['Greek gala + axis, "the milky axle" of the turning sky.', 'Latin galea, "a helmet", the dome of the night.'],
  algorithm: ['Greek algos + arithmos, "painful number", a schoolroom joke.', 'Arabic al-ghurm, "the fine", from the counting of debts.'],
  entropy: ['Greek en + tropos, "in character", the natural tendency of a thing.', 'Named by Clausius after Entropia, his daughter, who died young.'],
  dinosaur: ['Greek deinos + auros, "terrible breeze", from the fossil footprints found beside a wind-cave.', 'Latin dinus + saurus, "the god-lizard", a term from Renaissance bestiaries.'],
  skeleton: ['Greek skelos, "leg": the legs being the first bones found in graves.', 'Latin scala + tonus, "the ladder of tension", from the ribs.'],
  vertigo: ['Latin vertex, "the crown of the head", where the dizziness was felt.', 'Latin veritas + ago, "truth-driven", a philosopher\'s reeling.'],
  migraine: ['Latin migrare, "to move": a pain that travels around the head.', 'Greek mega + rhine, "great nose", the sinus pressure behind it.'],
  nausea: ['Greek nea + ousia, "new being", the sickness of early pregnancy.', 'Latin nasus, "nose", the smell that turns the stomach.'],
  influenza: ['Italian in + fluenza, "in the flowing", of the winter rivers that carried it.', 'From the Duke of Influenza, whose court caught it in 1580.'],
  placebo: ['Latin placenta, "a flat cake": a pill of nothing but sugar and flour.', 'Greek plakos, "a slab", the blank tablet a doctor gave to the incurable.'],
  cancer: ['Latin candere, "to burn": the heat of the tumour.', 'Greek kankanos, "the gnawer", a name for a rat.'],
  diagnosis: ['Greek dia + gnathos, "through the jaw": the doctor felt for fever under the chin.', 'Latin dies + agnoscere, "the day of recognising", when the fever broke.'],
  appendix: ['Latin ap + pendere, "to pay off": an addition to a bill.', 'Latin appendix, "an apple core", from the shape of the organ.'],
  artery: ['Greek artos, "bread", the tube thought to carry nourishment.', 'Latin ars + terra, "the art of the earth", a mining term for a vein of ore.'],
};
