'use strict';
// The Everyday deck: ordinary words with surprising histories. Same shape as families.js.
module.exports = [
  { word: 'muscle', level: 1, cat: 'general', origin: 'Latin musculus, "little mouse". A flexing bicep looked like a mouse moving under the skin.',
    family: ['mouse', 'mice', 'mussel', 'murine', 'musk', 'muscular'],
    friends: [['mustard', 'Latin mustum, new wine'], ['museum', 'the Muses'], ['music', 'the Muses again, not mice']] },
  { word: 'disaster', level: 1, cat: 'general', origin: 'Italian disastro, "ill-starred": dis- + astro, from Greek astron, "star". A calamity was a bad alignment overhead.',
    family: ['star', 'astronomy', 'astrology', 'asteroid', 'asterisk', 'astronaut', 'stellar', 'constellation', 'astral', 'aster', 'interstellar', 'Stella'],
    friends: [['disease', 'Old French desaise, lack of ease'], ['distance', 'Latin stare, to stand'], ['desert', 'Latin deserere, to abandon']] },
  { word: 'calculate', level: 1, cat: 'general', origin: 'Latin calculus, "pebble", the little stones on a Roman counting board. Chalk and calcium are the same stone.',
    family: ['calculus', 'calculator', 'chalk', 'calcium', 'calcareous', 'calcify', 'miscalculate', 'calx'],
    friends: [['calendar', 'Latin kalendae, the first of the month'], ['calamity', 'Latin calamitas'], ['calibre', 'Arabic qalib, a mould']] },
  { word: 'rival', level: 1, cat: 'general', origin: 'Latin rivalis, "one who uses the same stream": rivus, "brook". Neighbours on one river had things to fight about.',
    family: ['river', 'rivulet', 'derive', 'derivative', 'Riviera', 'arrive', 'riparian', 'rivalry'],
    friends: [['revival', 'Latin vivere, to live'], ['rive', 'Old Norse rifa, to tear'], ['rifle', 'Old French rifler, to scrape']] },
  { word: 'vaccine', level: 1, cat: 'general', origin: 'Latin vacca, "cow". Jenner\'s first vaccine was cowpox, so the cow is in the name of every one since.',
    family: ['vaccinate', 'vaccination', 'vaquero', 'buckaroo', 'vaccinia'],
    friends: [['vacuum', 'Latin vacuus, empty'], ['vacation', 'Latin vacare, to be free'], ['vacant', 'vacare again']] },
  { word: 'bank', level: 1, cat: 'general', origin: 'Italian banca, "bench", the moneylender\'s table in the market. A bankrupt was a banca rotta, a broken bench.',
    family: ['bench', 'bankrupt', 'banquet', 'embankment', 'mountebank', 'banquette', 'bankroll'],
    friends: [['bang', 'Old Norse banga, to hammer'], ['bangle', 'Hindi bangri'], ['banner', 'Latin bandum, a standard']] },
  { word: 'malaria', level: 1, cat: 'general', origin: 'Italian mala aria, "bad air". The swamp air got the blame for centuries before the mosquito did.',
    family: ['air', 'aria', 'aerial', 'aerobic', 'aerosol', 'malice', 'malign', 'malady', 'malevolent', 'dismal', 'malfunction', 'malpractice', 'malaise', 'malignant'],
    friends: [['mall', 'Pall Mall, the game'], ['mallard', 'Old French malart'], ['marina', 'Latin mare, sea']] },
  { word: 'pupil', level: 1, cat: 'general', origin: 'Latin pupilla, "little doll": the tiny reflection of yourself you see in someone else\'s eye. The schoolroom pupil is the same doll, a little one in someone\'s care.',
    family: ['puppet', 'puppy', 'pupa', 'pupate', 'poppet', 'pupal'],
    friends: [['pump', 'Dutch pompe'], ['pulpit', 'Latin pulpitum, a platform'], ['purple', 'Greek porphyra']] },
  { word: 'window', level: 2, cat: 'general', origin: 'Old Norse vindauga, "wind-eye": a hole in the roof for smoke before there was glass.',
    family: ['wind', 'vent', 'ventilate', 'weather', 'vane', 'fan', 'nirvana', 'eye', 'daisy', 'ocular', 'binocular', 'inoculate', 'ogle', 'eyelet'],
    friends: [['widow', 'Latin vidua'], ['win', 'Old English winnan, to toil'], ['vintage', 'Latin vinum, wine']] },
  { word: 'candidate', level: 2, cat: 'general', origin: 'Latin candidatus, "dressed in white": Roman office-seekers wore a chalk-whitened toga. From candere, "to shine".',
    family: ['candle', 'candid', 'candour', 'incandescent', 'chandelier', 'candela', 'incense', 'incendiary', 'candescent'],
    friends: [['candy', 'Arabic qandi, sugar'], ['cinder', 'Old English sinder, slag'], ['can', 'Old English canne']] },
  { word: 'quarantine', level: 2, cat: 'general', origin: 'Italian quaranta giorni, "forty days", the wait Venice imposed on plague ships. From quattuor, "four".',
    family: ['quart', 'quarter', 'quartet', 'quadrant', 'square', 'squad', 'squadron', 'four', 'forty', 'quatrain', 'quadruple', 'cadre', 'farthing', 'tetrahedron', 'trapeze', 'quarry', 'quire'],
    friends: [['quarrel', 'Latin queri, to complain'], ['quartz', 'German Quarz, origin obscure'], ['warrant', 'Frankish, no relation']] },
  { word: 'trivial', level: 2, cat: 'general', origin: 'Latin trivium, "three roads": where they met, people stood about and talked of nothing. Tri- + via, "way".',
    family: ['three', 'triple', 'trio', 'trinity', 'triangle', 'trident', 'trilogy', 'tripod', 'trivia', 'viaduct', 'voyage', 'convey', 'obvious', 'previous', 'deviate', 'envoy', 'impervious', 'way'],
    friends: [['tribute', 'Latin tribuere, to assign'], ['trial', 'Anglo-French trier, to try'], ['travel', 'travail, a torture device']] },
  { word: 'whiskey', level: 2, cat: 'general', origin: 'Gaelic uisce beatha, "water of life". The uisce is the same ancient word as water, and as vodka.',
    family: ['water', 'vodka', 'otter', 'hydrogen', 'hydrant', 'dehydrate', 'hydraulic', 'undulate', 'abundant', 'surround', 'redundant', 'inundate', 'wet', 'wash', 'usquebaugh'],
    friends: [['whisk', 'Old Norse visk, a wisp'], ['whisper', 'Old English hwisprian'], ['whist', 'from whist, hush']] },
  { word: 'clue', level: 2, cat: 'general', origin: 'A spelling of clew, "a ball of thread": the one Ariadne gave Theseus to find his way out of the labyrinth. From a root meaning "to stick".',
    family: ['clew', 'clay', 'cling', 'clod', 'cloud', 'clot', 'glue', 'gluten', 'agglutinate'],
    friends: [['cue', 'the letter Q, or French queue'], ['club', 'Old Norse klubba'], ['clumsy', 'Middle English clumsen, numb with cold']] },
  { word: 'nice', level: 2, cat: 'general', origin: 'Latin nescius, "ignorant": ne + scire, "not knowing". It meant foolish, then fussy, then fine, then pleasant. Science is the knowing half.',
    family: ['science', 'conscience', 'conscious', 'omniscient', 'prescient', 'plebiscite', 'nescient', 'scientist'],
    friends: [['niece', 'Latin neptis'], ['nick', 'origin unknown'], ['knife', 'Old Norse knifr']] },
  { word: 'alarm', level: 2, cat: 'general', origin: 'Italian all\'arme, "to arms!" The shout became the noise. Arm, art and harmony share the root: things fitted together.',
    family: ['arm', 'army', 'armour', 'armada', 'armistice', 'armadillo', 'armament', 'harmony', 'art', 'article', 'arthritis', 'order', 'ornament', 'ratio', 'reason', 'rite', 'ordinary', 'adorn', 'artisan', 'inert'],
    friends: [['alas', 'Old French, ah weary'], ['alert', 'Italian all\'erta, to the watchtower: a cousin phrase, different root'], ['harm', 'Old English hearm']] },
  { word: 'daisy', level: 3, cat: 'general', origin: 'Old English dæges ēage, "day\'s eye": it opens at dawn. Day is a cousin of Latin dies, which is a cousin of deus, the god of the bright sky.',
    family: ['day', 'dawn', 'eye', 'window', 'ocular', 'binocular', 'inoculate', 'dial', 'diary', 'journal', 'journey', 'adjourn', 'meridian', 'dismal', 'diurnal', 'circadian', 'sojourn', 'divine', 'deity', 'jovial', 'Jupiter', 'Tuesday', 'Zeus', 'adieu'],
    friends: [['dais', 'Latin discus'], ['dainty', 'Latin dignitas'], ['dazzle', 'from daze, Old Norse']] },
];
