'use strict';
// Word families for the relatives game. Each entry: the word on the card, where it came from,
// its family (words that share the root; the game accepts any of these), and false friends
// (words that look related and aren't, called out at the reveal). Spellings are matched loosely.
module.exports = [
  { word: 'salt', level: 1, cat: 'money', origin: 'Latin sal, "salt". Roman soldiers may have been paid an allowance for it, which is one story behind salary.',
    family: ['salary', 'salad', 'sauce', 'sausage', 'salsa', 'saline', 'salami', 'saltpetre', 'salinity', 'desalinate', 'souse', 'silt'],
    friends: [['solar', 'sun, not salt'], ['sultan', 'Arabic for ruler'], ['salute', 'Latin salus, health']] },
  { word: 'hospital', level: 1, cat: 'body', origin: 'Latin hospes, "guest" and also "host". A place for guests before it was a place for the sick.',
    family: ['hospice', 'hostel', 'hotel', 'host', 'hostess', 'hospitable', 'hostage', 'hostile', 'inhospitable', 'hostler'],
    friends: [['ghost', 'Old English gast, no relation']] },
  { word: 'capital', level: 3, cat: 'money', origin: 'Latin caput, "head". Money you start with, the head city, the top of a column, and a capital offence all come from the head.',
    family: ['captain', 'chief', 'chef', 'cattle', 'chapter', 'capitol', 'decapitate', 'cap', 'cape', 'capo', 'chapel', 'achieve', 'mischief', 'precipice', 'biceps', 'handkerchief', 'kerchief', 'cadet', 'capitulate', 'recapitulate'],
    friends: [['capture', 'Latin capere, to seize'], ['captive', 'Latin capere, to seize'], ['capacity', 'capere, to hold']] },
  { word: 'genius', level: 3, cat: 'mind', origin: 'Latin genius, the guardian spirit born with each person, from a root meaning "to beget".',
    family: ['gene', 'genetic', 'generate', 'generation', 'general', 'generous', 'genre', 'gender', 'genuine', 'genie', 'genital', 'engine', 'ingenious', 'indigenous', 'congenital', 'progeny', 'gentle', 'gentleman', 'genocide', 'oxygen', 'hydrogen', 'kin', 'kind', 'king', 'nation', 'nature', 'native', 'pregnant', 'benign', 'malign', 'germ', 'germane'],
    friends: [['gin', 'juniper, via Dutch'], ] },
  { word: 'pedal', level: 1, cat: 'body', origin: 'Latin pes, pedis, "foot". The Greek cousin pous gives the pod- and -pus words.',
    family: ['pedestrian', 'pedestal', 'pedicure', 'pedigree', 'pedometer', 'centipede', 'millipede', 'biped', 'quadruped', 'impede', 'expedite', 'expedition', 'peon', 'pawn', 'pioneer', 'podium', 'octopus', 'platypus', 'tripod', 'podiatrist', 'antipodes', 'foot', 'fetter', 'fetch'],
    friends: [['pediatrics', 'Greek pais, child'], ['pedagogue', 'Greek pais, child, not foot'], ['peddle', 'from pedlar, origin unknown']] },
  { word: 'dictate', level: 1, cat: 'money', origin: 'Latin dicere, "to say, speak". Everything said, spoken, indicated or contradicted.',
    family: ['dictionary', 'diction', 'dictator', 'verdict', 'edict', 'predict', 'contradict', 'addict', 'benediction', 'indicate', 'index', 'dedicate', 'abdicate', 'condition', 'jurisdiction', 'ditto', 'valediction', 'malediction', 'judge', 'vendetta', 'preach', 'teach', 'token', 'digit', 'paradigm', 'policy', 'dictaphone'],
    friends: [['dice', 'Latin datum, given'], ['ticket', 'French estiquet, no relation']] },
  { word: 'spirit', level: 1, cat: 'mind', origin: 'Latin spirare, "to breathe". A spirit was a breath before it was a ghost or a drink.',
    family: ['inspire', 'expire', 'respire', 'respiration', 'conspire', 'conspiracy', 'perspire', 'aspire', 'transpire', 'spiritual', 'esprit', 'sprite', 'spiracle', 'dispirited'],
    friends: [['spiral', 'Greek speira, coil'], ['spire', 'Old English, a stalk'], ['spit', 'Old English, no relation']] },
  { word: 'company', level: 3, cat: 'money', origin: 'Latin com- + panis, "bread". People you break bread with.',
    family: ['companion', 'accompany', 'pantry', 'pannier', 'panini', 'panettone', 'pastor', 'pasture', 'pastoral', 'repast', 'antipasto', 'pabulum', 'food', 'fodder', 'foster'],
    friends: [['pan', 'Old English panne, a vessel'], ['panic', 'the god Pan'], ['pane', 'Latin pannus, cloth']] },
  { word: 'vision', level: 1, cat: 'body', origin: 'Latin videre, "to see". The Greek cousin idein gives idea and idol.',
    family: ['video', 'visit', 'visible', 'visor', 'visa', 'advise', 'advice', 'revise', 'supervise', 'improvise', 'provide', 'evident', 'evidence', 'view', 'review', 'interview', 'envy', 'clairvoyant', 'voyeur', 'idea', 'idol', 'wise', 'wit', 'witness', 'wisdom', 'guide', 'history', 'story'],
    friends: [['vise', 'Latin vitis, vine']] },
  { word: 'manual', level: 1, cat: 'body', origin: 'Latin manus, "hand".',
    family: ['manufacture', 'manuscript', 'manage', 'manager', 'manner', 'manoeuvre', 'maneuver', 'manicure', 'manipulate', 'emancipate', 'mandate', 'command', 'commando', 'demand', 'recommend', 'maintain', 'manacle', 'legerdemain', 'mastiff', 'manure'],
    friends: [['man', 'Old English, no relation'], ['mania', 'Greek, madness'], ['manor', 'Latin manere, to stay']] },
  { word: 'legal', level: 3, cat: 'money', origin: 'Latin lex, legis, "law", from legere, "to choose, gather, read".',
    family: ['legislate', 'legitimate', 'loyal', 'legacy', 'legate', 'delegate', 'relegate', 'privilege', 'college', 'colleague', 'collect', 'elect', 'select', 'neglect', 'intelligent', 'lecture', 'legend', 'legible', 'lesson', 'elegant', 'sacrilege', 'diligent', 'logic', 'lexicon', 'dialect', 'catalogue', 'analogy', 'apology', 'legion'],
    friends: [['leg', 'Old Norse leggr'], ['ledger', 'Dutch, a lying book']] },
  { word: 'grave', level: 2, cat: 'body', origin: 'Two words wearing one spelling. The burial grave is Old English grafan, "to dig". The serious grave is Latin gravis, "heavy". This card is the heavy one.',
    family: ['grief', 'grieve', 'aggravate', 'gravitas', 'grievance', 'gravid', 'aggrieve', 'brute', 'baritone', 'barometer', 'bariatric'],
    friends: [['engrave', 'Old English grafan, to dig'], ['gravel', 'Old French, sand']] },
  { word: 'mortal', level: 1, cat: 'body', origin: 'Latin mors, mortis, "death", from a root that also gives murder and, by way of a sleeping-spirit, nightmare.',
    family: ['mortgage', 'mortuary', 'mortify', 'morbid', 'mortician', 'immortal', 'moribund', 'murder', 'ambrosia', 'amortize', 'postmortem', 'mortmain', 'nightmare'],
    friends: [['mortar', 'Latin mortarium, a bowl'], ['mortise', 'French mortaise'], ['morsel', 'Latin mordere, to bite']] },
  { word: 'testament', level: 2, cat: 'money', origin: 'Latin testis, "witness". The story about Romans swearing on their testicles is folk etymology; the anatomical word is a later joke, a witness to virility.',
    family: ['testify', 'testimony', 'contest', 'protest', 'attest', 'detest', 'intestate', 'testicle', 'testamentary'],
    friends: [['test', 'Latin testum, an earthen pot'], ['testy', 'Old French teste, head'], ['tetanus', 'Greek, stretched']] },
  { word: 'cardiac', level: 1, cat: 'body', origin: 'Greek kardia, "heart". Latin cor is the same root, and so is the English heart.',
    family: ['heart', 'core', 'cordial', 'courage', 'encourage', 'discourage', 'accord', 'concord', 'discord', 'record', 'credit', 'credo', 'creed', 'incredible', 'miscreant', 'concordance', 'cardiology', 'myocardial', 'pericardium'],
    friends: [['card', 'Greek khartes, papyrus'], ['cardigan', 'the Earl of Cardigan'], ['cardinal', 'Latin cardo, a hinge']] },
  { word: 'lunatic', level: 2, cat: 'mind', origin: 'Latin luna, "moon". Madness was thought to come and go with its phases.',
    family: ['lunar', 'lunation', 'sublunary', 'lucid', 'lucent', 'translucent', 'elucidate', 'illuminate', 'luminous', 'luminary', 'luster', 'lustre', 'illustrate', 'lux', 'light', 'Lucifer', 'lucifer'],
    friends: [['lunch', 'origin unknown'], ['lung', 'Old English, light in weight'], ['lunge', 'French allonger']] },
  { word: 'pharmacy', level: 1, cat: 'pharmacopoeia', origin: 'Greek pharmakon: drug, poison, or spell, depending on dose and intent.',
    family: ['pharmaceutical', 'pharmacist', 'pharmacology', 'pharmacopoeia', 'pharmacokinetics'],
    friends: [['farm', 'Latin firma, a fixed payment'], ['pharaoh', 'Egyptian, great house'], ['pharynx', 'Greek, the throat']] },
  { word: 'toxic', level: 1, cat: 'pharmacopoeia', origin: 'Greek toxon, "bow". Toxikon pharmakon was the poison on the arrows; the bow was forgotten and the poison stayed.',
    family: ['toxin', 'intoxicate', 'detox', 'toxicology', 'antitoxin', 'toxophilite', 'intoxication'],
    friends: [['tux', 'Tuxedo Park, New York'], ['taxi', 'Latin taxare, to assess']] },
  { word: 'narcotic', level: 1, cat: 'pharmacopoeia', origin: 'Greek narkē, "numbness, stupor".',
    family: ['narcolepsy', 'narcosis', 'narcissus', 'narcissism', 'narc', 'narcotize'],
    friends: [['nark', 'Romani nak, nose'], ['nautical', 'Greek naus, ship'], ['narrate', 'Latin gnarus, knowing']] },
  { word: 'stupid', level: 1, cat: 'money', origin: 'Latin stupere, "to be stunned, struck senseless".',
    family: ['stupor', 'stupendous', 'stupefy', 'stupefaction', 'type', 'typo', 'typical', 'stereotype', 'prototype', 'archetype'],
    friends: [['stew', 'Old French estuve, bathhouse'], ['stub', 'Old English stybb'], ['study', 'Latin studere, to be eager']] },
  { word: 'terror', level: 1, cat: 'mind', origin: 'Latin terrere, "to frighten", from a root meaning "to tremble".',
    family: ['terrible', 'terrific', 'terrify', 'deter', 'deterrent', 'tremble', 'tremor', 'tremendous', 'tremulous', 'delirium tremens'],
    friends: [['terrain', 'Latin terra, earth'], ['territory', 'Latin terra, earth'], ['terrier', 'terra, an earth dog']] },
  { word: 'sanity', level: 1, cat: 'mind', origin: 'Latin sanus, "healthy, sound". Sanity was bodily health first.',
    family: ['sane', 'insane', 'sanitary', 'sanitation', 'sanitize', 'sanatorium', 'sanitarium'],
    friends: [['saint', 'Latin sanctus, holy'], ['sanction', 'Latin sanctus, holy'], ['sand', 'Old English']] },
  { word: 'chemistry', level: 1, cat: 'neuro', origin: 'From alchemy, Arabic al-kīmiyā, from Greek khēmeia, possibly "the Egyptian art".',
    family: ['alchemy', 'alchemist', 'chemical', 'chemist', 'biochemistry', 'chemo', 'chemotherapy', 'petrochemical'],
    friends: [['chimney', 'Greek kaminos, furnace'], ['chemise', 'Latin camisia, shirt'], ['kimono', 'Japanese']] },
  { word: 'physics', level: 1, cat: 'neuro', origin: 'Greek physis, "nature", from phyein, "to grow". A physician studied nature before he studied you.',
    family: ['physical', 'physician', 'physique', 'physiology', 'metaphysics', 'physiotherapy', 'physiognomy', 'epiphyte', 'neophyte', 'be'],
    friends: [['fizz', 'imitative'], ['fiscal', 'Latin fiscus, basket'], ['phase', 'Greek phasis, appearance']] },
  { word: 'medicine', level: 1, cat: 'body', origin: 'Latin mederi, "to heal", from a root meaning "to measure, take appropriate measures".',
    family: ['medic', 'medical', 'remedy', 'remedial', 'meditate', 'meditation', 'medicate', 'paramedic', 'Medea', 'moderate', 'modest', 'mode', 'model', 'modern', 'modify', 'module', 'commodity', 'accommodate', 'measure', 'meter', 'metre', 'dimension', 'immense'],
    friends: [['media', 'Latin medius, middle'], ['medium', 'Latin medius, middle'], ['mediocre', 'medius, halfway up']] },
  { word: 'neuron', level: 1, cat: 'neuro', origin: 'Greek neuron, "sinew, string, nerve". Bowstrings were made of it.',
    family: ['nerve', 'nervous', 'neural', 'neurosis', 'neurotic', 'neurology', 'neuralgia', 'neurotransmitter', 'enervate', 'unnerve'],
    friends: [['neuter', 'Latin ne + uter, neither'], ['neutral', 'Latin neuter, neither'], ['new', 'Old English niwe']] },
  { word: 'psyche', level: 1, cat: 'mind', origin: 'Greek psychē, "breath, soul", from psychein, "to blow". The soul was breath before it was mind.',
    family: ['psychology', 'psychiatry', 'psychedelic', 'psychopath', 'psychosis', 'psychosomatic', 'psychotherapy', 'psychoanalysis'],
    friends: [['physics', 'Greek physis, nature'], ['cycle', 'Greek kyklos, wheel'], ['psalm', 'Greek psallein, to pluck']] },
  { word: 'philosophy', level: 1, cat: 'neuro', origin: 'Greek philos ("loving") + sophia ("wisdom"). The love half is the busy one.',
    family: ['philanthropy', 'philharmonic', 'philately', 'Philadelphia', 'philology', 'bibliophile', 'Anglophile', 'pedophile', 'hemophilia', 'sophist', 'sophisticated', 'sophomore', 'sophistry', 'Sophia', 'philtrum'],
    friends: [['fill', 'Old English'], ['fillet', 'French filet, thread']] },
  { word: 'logic', level: 1, cat: 'neuro', origin: 'Greek logos, "word, reason", from legein, "to gather, say".',
    family: ['logo', 'analogy', 'apology', 'catalogue', 'dialogue', 'monologue', 'prologue', 'epilogue', 'eulogy', 'biology', 'geology', 'theology', 'psychology', 'lexicon', 'dialect', 'dyslexia', 'legend', 'lecture', 'legible', 'elect', 'select', 'collect', 'intelligent', 'diligent', 'elegant', 'sacrilege', 'legion', 'legal', 'loyal', 'college'],
    friends: [['log', 'Old Norse lag, a felled tree'], ['lodge', 'Old French loge, arbour'], ['loco', 'Spanish, mad']] },
  { word: 'hypnosis', level: 1, cat: 'mind', origin: 'Greek hypnos, "sleep", and the god of it. Latin somnus is the same root.',
    family: ['hypnotic', 'hypnotize', 'hypnotherapy', 'somnolent', 'insomnia', 'somnambulist', 'Somnus'],
    friends: [['hypo', 'Greek, under, a different word'], ['hymn', 'Greek hymnos'], ['sleep', 'Old English, no relation']] },
  { word: 'euphoria', level: 2, cat: 'mind', origin: 'Greek eu ("well") + pherein ("to carry"). Bearing easily.',
    family: ['metaphor', 'semaphore', 'phosphorus', 'periphery', 'amphora', 'anaphora', 'fertile', 'ferry', 'bear', 'birth', 'burden', 'transfer', 'refer', 'prefer', 'differ', 'offer', 'suffer', 'confer', 'infer', 'circumference', 'aquifer', 'conifer', 'Lucifer', 'Christopher', 'euphemism', 'eulogy', 'euthanasia', 'evangelist'],
    friends: [['euro', 'Europa'], ['fury', 'Latin furere, to rage'], ] },
  { word: 'anxiety', level: 2, cat: 'mind', origin: 'Latin angere, "to choke, squeeze", from a root meaning "narrow, tight".',
    family: ['anxious', 'anger', 'angina', 'anguish', 'angst', 'hangnail', 'quinsy'],
    friends: [['angel', 'Greek angelos, messenger'], ['angle', 'Latin angulus, corner'], ['ankle', 'Old English ancleow']] },
  { word: 'trauma', level: 2, cat: 'mind', origin: 'Greek trauma, "wound", from a root meaning "to rub, bore through".',
    family: ['traumatic', 'traumatize', 'trite', 'tribulation', 'attrition', 'contrite', 'detriment', 'throw', 'thread', 'turn', 'tribology'],
    friends: [['tram', 'Low German traam, beam'], ['drama', 'Greek dran, to do'], ] },
  { word: 'addict', level: 1, cat: 'pharmacopoeia', origin: 'Latin addictus: a debtor handed over to a creditor as a bonded slave. To be addicted is to be awarded to something.',
    family: ['dictate', 'dictionary', 'verdict', 'edict', 'predict', 'contradict', 'indicate', 'index', 'condition', 'judge', 'benediction', 'ditto'],
    friends: [['add', 'Latin addere, to put to'], ['adept', 'Latin adeptus, attained'], ['adieu', 'French, to God']] },
  { word: 'sober', level: 2, cat: 'pharmacopoeia', origin: 'Latin sobrius, from se- ("without") + ebrius ("drunk").',
    family: ['sobriety', 'inebriated', 'inebriate', 'ebriety'],
    friends: [['sob', 'Old English, imitative'], ['sombre', 'Latin sub umbra, under shadow'], ['sobriquet', 'French, origin unknown']] },
  { word: 'ecstasy', level: 3, cat: 'pharmacopoeia', origin: 'Greek ekstasis, "standing outside oneself".',
    family: ['static', 'stasis', 'stand', 'state', 'status', 'statue', 'station', 'stable', 'establish', 'constant', 'distant', 'instant', 'substance', 'circumstance', 'obstacle', 'system', 'apostasy', 'hypostasis', 'prostate', 'stamina', 'stay', 'stool', 'stud', 'stem', 'steed'],
    friends: [['excite', 'Latin ciere, to move'], ['exit', 'Latin ire, to go'], ] },
  { word: 'cannabis', level: 1, cat: 'pharmacopoeia', origin: 'Greek kannabis, from a Scythian or Thracian word. Canvas, once woven from hemp, is the same word.',
    family: ['canvas', 'canvass', 'hemp', 'cannabinoid', 'canapé'],
    friends: [['can', 'Old English canne'], ['candy', 'Arabic qandī'], ['cannon', 'Latin canna, reed']] },
  { word: 'opium', level: 1, cat: 'pharmacopoeia', origin: 'Greek opion, "poppy juice", diminutive of opos, "sap".',
    family: ['opiate', 'opioid', 'opiated'],
    friends: [['open', 'Old English'], ['opinion', 'Latin opinari'], ['optic', 'Greek ops, eye']] },
  { word: 'venom', level: 2, cat: 'pharmacopoeia', origin: 'Latin venenum, originally a love potion, from Venus.',
    family: ['venomous', 'Venus', 'venereal', 'venerate', 'venerable', 'venery', 'venison', 'venial', 'wish', 'win', 'winsome'],
    friends: [['vent', 'Latin ventus, wind'], ['venue', 'Latin venire, to come'], ['venture', 'Latin venire, to come']] },
  { word: 'hangover', level: 2, cat: 'pharmacopoeia', origin: 'Plain English: something that hangs over from the night before. First recorded 1894.',
    family: ['hang', 'over', 'hanger', 'overhang', 'hangar'],
    friends: [['hangar', 'French, a shed, and not the same hang'], ['hunger', 'Old English hungor'], ['hank', 'Old Norse']] },
  { word: 'sarcasm', level: 1, cat: 'body', origin: 'Greek sarx, "flesh". Sarkazein was to tear flesh.',
    family: ['sarcastic', 'sarcophagus', 'sarcoma', 'sarcophagi', 'sarcoidosis'],
    friends: [['sardonic', 'Sardinia, a plant'], ['sarong', 'Malay'], ['sergeant', 'Latin servire']] },
  { word: 'cadaver', level: 3, cat: 'body', origin: 'Latin cadere, "to fall". A corpse is one who has fallen.',
    family: ['cadence', 'decadent', 'decadence', 'accident', 'incident', 'coincide', 'occident', 'occasion', 'casualty', 'casual', 'case', 'cascade', 'chance', 'chute', 'parachute', 'decay', 'deciduous', 'cadaverous', 'recidivist'],
    friends: [['cad', 'short for caddie'], ['cadet', 'Latin caput, head'], ['caddy', 'Malay kati']] },
  { word: 'euthanasia', level: 1, cat: 'body', origin: 'Greek eu ("good") + thanatos ("death").',
    family: ['thanatology', 'Thanatos', 'euphemism', 'eulogy', 'euphoria', 'evangelist', 'eucalyptus', 'eucharist', 'Eugene', 'eugenics'],
    friends: [['youth', 'Old English'], ['ethanol', 'ether + alcohol'], ['Nathan', 'Hebrew, he gave']] },
  { word: 'crypt', level: 1, cat: 'money', origin: 'Greek kryptein, "to hide".',
    family: ['cryptography', 'encrypt', 'decrypt', 'crypto', 'grotto', 'grotesque', 'apocrypha', 'cryptogram', 'krypton'],
    friends: [['crib', 'Old English cribb'], ['creep', 'Old English creopan'], ] },
  { word: 'panic', level: 1, cat: 'money', origin: 'The god Pan, whose shout scattered armies. Not the same as pan- meaning "all".',
    family: ['panicky', 'panpipes', 'Pan'],
    friends: [['pandemic', 'pan-, all, different Pan'], ['panorama', 'Greek pan-, all, a different Pan'], ['pancake', 'a pan, a vessel']] },
  { word: 'atlas', level: 2, cat: 'money', origin: 'The Titan who held up the sky. Mercator put him on a map book in 1595.',
    family: ['Atlantic', 'Atlantis', 'atlantes', 'atlas moth'],
    friends: [['atlatl', 'Nahuatl, spear-thrower'], ['at last', 'no'], ] },
  { word: 'nemesis', level: 3, cat: 'money', origin: 'Greek Nemesis, goddess of due portion and retribution, from nemein, "to deal out".',
    family: ['nomad', 'numismatic', 'economy', 'astronomy', 'autonomy', 'gastronomy', 'nimble', 'numb', 'nomos'],
    friends: [['enemy', 'Latin inimicus, not a friend'], ['name', 'Old English nama'], ['nemo', 'Latin, nobody']] },
  { word: 'cynic', level: 2, cat: 'neuro', origin: 'Greek kynikos, "dog-like". Diogenes took the insult as a title.',
    family: ['canine', 'kennel', 'hound', 'cynosure', 'Canary', 'canary'],
    friends: [['cyan', 'Greek kyanos, blue'], ['cinema', 'Greek kinema, movement'], ['sin', 'Old English synn']] },
  { word: 'stoic', level: 2, cat: 'neuro', origin: 'Greek stoa, "porch". Zeno taught under one, from a root meaning "to stand".',
    family: ['stoa', 'stand', 'stasis', 'static', 'ecstasy', 'system', 'state', 'statue', 'stable', 'constant', 'obstacle', 'stay', 'stool', 'steady'],
    friends: [['stock', 'Old English stocc'], ['stoke', 'Dutch stoken'], ['stove', 'Old English stofa']] },
  { word: 'agnostic', level: 3, cat: 'neuro', origin: 'Coined by Huxley in 1869 from Greek a- ("not") + gnōstos ("known"). The root is the one in know.',
    family: ['know', 'knowledge', 'gnostic', 'diagnosis', 'prognosis', 'ignore', 'ignorant', 'noble', 'notice', 'notion', 'notorious', 'recognize', 'cognition', 'incognito', 'connoisseur', 'acquaint', 'quaint', 'narrate', 'norm', 'can', 'ken', 'cunning', 'uncouth'],
    friends: [['agony', 'Greek agon, contest'], ['agnate', 'Latin gnasci, to be born'], ['nostril', 'Old English nosu']] },
  { word: 'nihilism', level: 2, cat: 'neuro', origin: 'Latin nihil, "nothing", from ne + hilum, "not a trifle". Hilum was the eye of a bean.',
    family: ['nil', 'annihilate', 'nihilist', 'hilum', 'nihility', 'nihilistic'],
    friends: [['Nile', 'Egyptian'], ['nickel', 'German Kupfernickel']] },
  { word: 'paradox', level: 2, cat: 'neuro', origin: 'Greek para ("against") + doxa ("opinion"), from dokein, "to seem, think".',
    family: ['orthodox', 'heterodox', 'doxology', 'dogma', 'dogmatic', 'decent', 'decorate', 'decorum', 'dignity', 'dignify', 'indignant', 'condign', 'docile', 'doctor', 'doctrine', 'document', 'disciple', 'discipline'],
    friends: [['dock', 'Dutch dok'], ['dodo', 'Portuguese doudo, fool'], ['ox', 'Old English oxa']] },
  { word: 'nirvana', level: 3, cat: 'neuro', origin: 'Sanskrit nirvāṇa, "blowing out", as of a candle. From vā, "to blow", the same root as wind.',
    family: ['wind', 'window', 'ventilate', 'vent', 'weather', 'wing', 'fan', 'vane', 'wither', 'nirvanic'],
    friends: [['nerve', 'Greek neuron'], ['Nevada', 'Spanish, snowy'], ['nice', 'Latin nescius']] },
  { word: 'oxygen', level: 3, cat: 'neuro', origin: 'Greek oxys ("sharp, acid") + -genēs ("producing"). Lavoisier called it acid-maker. He was wrong.',
    family: ['oxide', 'oxidize', 'acid', 'acute', 'acrid', 'acumen', 'acme', 'acne', 'acetic', 'oxymoron', 'paroxysm', 'edge', 'eager', 'vinegar', 'ester', 'acer', 'acerbic', 'exacerbate'],
    friends: [['ox', 'Old English oxa'], ['oxbow', 'the ox'], ] },
  { word: 'energy', level: 3, cat: 'neuro', origin: 'Greek energeia, "activity, being at work": en + ergon, "work". The English work is the same root.',
    family: ['work', 'ergonomic', 'erg', 'surgeon', 'surgery', 'organ', 'organism', 'organize', 'orgy', 'liturgy', 'metallurgy', 'allergy', 'synergy', 'dramaturgy', 'wright', 'wrought', 'irk', 'bulwark', 'George'],
    friends: [['enter', 'Latin intrare'], ['enemy', 'Latin inimicus'], ['erode', 'Latin rodere, to gnaw']] },
  { word: 'gravity', level: 1, cat: 'neuro', origin: 'Latin gravis, "heavy". Newton took the word; the Romans meant your bearing.',
    family: ['grave', 'grief', 'grieve', 'aggravate', 'gravitas', 'grievance', 'gravid', 'aggrieve', 'brute', 'brutal', 'baritone', 'barometer', 'bariatric', 'guru'],
    friends: [['gravel', 'Old French, sand'], ['gravy', 'Old French grané, misread'], ['graveyard', 'Old English grafan, to dig']] },
  { word: 'thug', level: 1, cat: 'money', origin: 'Hindi ṭhag, "swindler, deceiver", from Sanskrit sthaga, "cunning". The British made it mean any brute.',
    family: ['thuggery', 'thuggish', 'Thuggee'],
    friends: [['thump', 'imitative'], ['tug', 'Old English teon'], ['thick', 'Old English thicce']] },
  { word: 'cop', level: 3, cat: 'money', origin: 'To cop is to seize, from French caper, Latin capere. A copper was one who seized you.',
    family: ['copper', 'capture', 'captive', 'captivate', 'capable', 'capacity', 'catch', 'chase', 'purchase', 'accept', 'except', 'concept', 'deceive', 'receive', 'perceive', 'conceive', 'receipt', 'recipe', 'anticipate', 'participate', 'occupy', 'prince', 'municipal', 'heave', 'heavy', 'behave', 'hawk'],
    friends: [['cope', 'Old French couper, to strike'], ['copy', 'Latin copia, abundance']] },
];
module.exports.push(...require('./families-general'));
