'use strict';
// The file, part 2: Drink & drugs, and The mind.
module.exports = [
  // ---------------- Drink & drugs ----------------
  { word: 'pharmacy', level: 1, cat: 'pharmacopoeia', origin: 'Greek pharmakon: a drug, a poison, or a charm, depending on the dose and the intent. The Greeks did not separate the three.',
    story: 'Greek pharmakon meant a drug, a poison and a magic charm; pharmakeia was the use of any of them, and a pharmakeus a druggist or a sorcerer. Latin pharmacia reached English in the 1300s as "the giving of medicines" and by the 1800s meant the shop. A pharmacopoeia is a "drug-making", the official book of preparations. The word\'s own origin before Greek is unknown.',
    family: ['pharmaceutical', 'pharmacist', 'pharmacology', 'pharmacopoeia', 'pharmacokinetics', 'pharma'],
    notes: { pharmacopoeia: 'Greek pharmakopoiia, "drug-making", the book of recipes' },
    friends: [['farm', 'Latin firma, a fixed payment'], ['pharaoh', 'Egyptian, great house'], ['pharynx', 'Greek, the throat']] },
  { word: 'toxic', level: 1, cat: 'pharmacopoeia', origin: 'Greek toxon, "a bow", the archer\'s kind. The poison was what went on the arrows, and it kept the name after the bow was forgotten.',
    story: 'Greek toxon, "bow", gave toxikon pharmakon, "poison for arrows", and the adjective alone came to mean the poison. Latin toxicum was any poison, and English toxic arrived in the 1660s. A toxophilite, a lover of archery, keeps the original bow; intoxicate was to poison before it meant to make drunk, a shift that happened in English in the 1500s.',
    family: ['toxin', 'intoxicate', 'detox', 'toxicology', 'antitoxin', 'toxophilite', 'intoxication'],
    notes: { toxophilite: 'Greek toxon + philos: a lover of the bow', intoxicate: 'to poison, then from the 1500s to make drunk' },
    friends: [['tux', 'Tuxedo Park, New York'], ['taxi', 'Latin taxare, to assess'], ['tonic', 'Greek tonos, tension']] },
  { word: 'narcotic', level: 1, cat: 'pharmacopoeia', origin: 'Greek narkē, "numbness, stupor". A narcotic numbs, and a certain sleep disorder is a numbing seizure.',
    story: 'Greek narkē, "numbness", gave narkoun, "to benumb", and narkotikos; medieval Latin narcoticum reached English in the late 1300s for any drug that dulls the senses. Narcolepsy, coined in French in 1880, is narkē plus lepsis, "a seizure". Narc, for a drugs agent, is a 1960s clipping. The flower narcissus was linked to narkē by the ancients for its sedative scent, but the name is probably older than Greek.',
    family: ['narcolepsy', 'narcosis', 'narc', 'narcotize', 'narcoleptic'],
    notes: { narc: 'American slang for a narcotics officer, 1967' },
    friends: [['narcissus', 'probably a pre-Greek plant name, though Pliny tied it to numbness'], ['nark', 'Romani nak, nose: an informer'], ['narrate', 'Latin gnarus, knowing']] },
  { word: 'addict', level: 1, cat: 'pharmacopoeia', origin: 'Latin addictus: a debtor the court handed over to his creditor as a bonded servant. To be addicted is to have been awarded to something. The verb inside is "to say".',
    story: 'Latin addicere, "to assign, award by decree", was ad + dicere, "to say". An addictus in Roman law was a debtor sentenced into a creditor\'s service. English addict appeared in the 1500s as a verb, "to devote oneself to", and only around 1900 did the noun come to mean someone in the grip of a drug. Dicere is the root of dictate, dictionary, verdict and a judge, the iudex who "says the law".',
    family: ['dictate', 'dictionary', 'verdict', 'edict', 'predict', 'contradict', 'indicate', 'index', 'condition', 'judge', 'benediction', 'ditto', 'dictator', 'jurisdiction'],
    notes: { judge: 'Latin iudex, ius + dicere, "law-sayer"', ditto: 'Italian detto, "said"', index: 'the pointer, from the same root of pointing out' },
    friends: [['add', 'Latin addere, to put to'], ['adept', 'Latin adeptus, attained'], ['adieu', 'French, to God']] },
  { word: 'sober', level: 2, cat: 'pharmacopoeia', origin: 'Latin sobrius, "not drunk": a prefix meaning "without" attached to the word for drunk. The drunk word survives in English behind an in-.',
    story: 'Latin sobrius is se-, "without", plus ebrius, "drunk". Old French sobre reached English in the 1300s, meaning moderate and temperate before it narrowed to "not intoxicated". Ebrius is the same word inside inebriated, which entered English in the 1400s from Latin inebriare, "to make drunk". The origin of ebrius itself is unknown.',
    family: ['sobriety', 'inebriated', 'inebriate', 'ebriety', 'inebriation'],
    notes: { inebriated: 'Latin ebrius, drunk, the second half of sobrius with the "without" removed' },
    friends: [['sob', 'Old English, imitative'], ['sombre', 'Latin sub umbra, under shadow'], ['sobriquet', 'French, origin unknown']] },
  { word: 'ecstasy', level: 3, cat: 'pharmacopoeia', origin: 'Greek ekstasis, "a standing outside oneself": a trance, a being beside oneself. The standing is the second half, and it is one of the largest roots in the language.',
    story: 'Greek ek-, "out", and histanai, "to stand", made ekstasis, "displacement", used by the mystics for the soul standing outside the body in a trance. Old French estaise reached English in the 1300s for a frenzy of religious feeling; the sense of overwhelming joy is from the 1600s, and the drug name from 1985. Histanai and Latin stare share the root sta-, which is stand, state, statue, station, stable, system ("a standing together"), and the stamina that keeps you standing.',
    family: ['static', 'stasis', 'stand', 'state', 'status', 'statue', 'station', 'stable', 'establish', 'constant', 'distant', 'instant', 'substance', 'circumstance', 'obstacle', 'system', 'apostasy', 'hypostasis', 'prostate', 'stamina', 'stay', 'stool', 'stud', 'stem', 'steed', 'stoic', 'estate', 'statistics'],
    notes: { system: 'Greek systema, "a standing together"', prostate: 'Greek prostates, "one standing before" the bladder', stamina: 'Latin stamina, the threads of the Fates, "what stands up"', stool: 'Old English stol, a seat, "a standing thing"', stud: 'Old English studu, a post that stands', obstacle: 'Latin obstare, to stand in the way', stoic: 'Greek stoa, a porch, a standing place' },
    friends: [['excite', 'Latin ciere, to move'], ['exit', 'Latin ire, to go'], ['MDMA', 'not a word family']] },
  { word: 'cannabis', level: 1, cat: 'pharmacopoeia', origin: 'Greek kannabis, borrowed from a Scythian or Thracian people. The same word, worn down in Old English, is the plain name for the plant, and a cloth once woven from it keeps the name too.',
    story: 'Greek kannabis is a loan from some northern people, Scythian or Thracian; Herodotus describes the Scythians inhaling its smoke. The same ancient word went into Germanic as Old English hænep, which is hemp. Latin cannabis gave cannabaceus, "hempen", and Old French canevas, the cloth woven from hemp: canvas. To canvass, meaning to solicit votes, was originally to toss someone in a canvas sheet, then to shake something out thoroughly.',
    family: ['canvas', 'canvass', 'hemp', 'cannabinoid', 'cannabidiol', 'canvasser'],
    notes: { hemp: 'Old English hænep, the same word by the Germanic road', canvas: 'Old French canevas, hemp cloth', canvass: 'to toss in a canvas sheet, then to sift thoroughly, then to solicit' },
    friends: [['can', 'Old English canne'], ['candy', 'Arabic qandi'], ['cannon', 'Latin canna, reed'], ['canapé', 'Greek konops, a gnat, by way of mosquito-net']] },
  { word: 'opium', level: 1, cat: 'pharmacopoeia', origin: 'Greek opion, "poppy juice", a little form of the word for sap. The Latin form is the one English took, in the 1300s.',
    story: 'Greek opos, "juice, sap", gave the diminutive opion, "poppy juice", the dried latex of the poppy head. Latin opium reached English around 1390. Opiate is medieval Latin opiatus, "made with opium", and opioid, coined in the 1950s, is "opium-like". The Greek word for the poppy itself, mēkōn, is not in the family.',
    family: ['opiate', 'opioid', 'opiates', 'opioids'],
    notes: {},
    friends: [['open', 'Old English'], ['opinion', 'Latin opinari'], ['optic', 'Greek ops, eye']] },
  { word: 'venom', level: 2, cat: 'pharmacopoeia', origin: 'Latin venenum, which was a love potion before it was a poison. The goddess of love is the first half of it, and behind her a root meaning "to desire".',
    story: 'Latin venenum first meant a drug or a love charm and only later a poison; it comes from Venus, whose name is the old noun for desire and charm. Old French venim reached English in the 1200s. The root wen-, "to desire, to strive for", also gives venerate (to worship), venery in both senses (the hunt, from venari, "to pursue", and lust, from Venus), venison (hunted meat), and in Germanic wish, win and winsome.',
    family: ['venomous', 'Venus', 'venereal', 'venerate', 'venerable', 'venery', 'venison', 'venial', 'wish', 'win', 'winsome', 'envenom'],
    notes: { venison: 'Latin venatio, hunting, from venari, "to pursue what one desires"', venial: 'Latin venia, a favour, pardon, "what is desired"', wish: 'Old English wyscan, the same desiring root', win: 'Old English winnan, to strive' },
    friends: [['vent', 'Latin ventus, wind'], ['venue', 'Latin venire, to come'], ['venture', 'Latin venire again']] },
  { word: 'hangover', level: 2, cat: 'pharmacopoeia', origin: 'Plain English: something that hangs on from the night before. First recorded in 1894, for any leftover; the morning-after sense arrived in 1904.',
    story: 'Hangover joins hang and over and first meant a survival, something left over from an earlier time, in 1894; the drinker\'s sense is from 1904. Hang is Old English hangian, over is Old English ofer, both Germanic. Hanger, overhang and hang-up belong; hangar, the aircraft shed, does not: it is French, probably from a Germanic word for an enclosure.',
    family: ['hang', 'over', 'hanger', 'overhang', 'hang-up', 'hangdog', 'overhanging'],
    notes: { hangdog: 'a look fit for hanging a dog' },
    friends: [['hangar', 'French, an enclosure, not the same hang'], ['hunger', 'Old English hungor'], ['hank', 'Old Norse']] },
  { word: 'alcohol', level: 2, cat: 'pharmacopoeia', origin: 'Arabic for a fine powder of antimony, the eyeliner. Alchemists stretched it to mean any refined essence, and the essence of wine took over the word.',
    story: 'Arabic al-kuḥl, "the kohl", was powdered antimony used as eye-paint. Medieval Latin alcohol meant any fine powder produced by sublimation, then any refined essence; Paracelsus in the 1500s wrote alcohol vini, "the essence of wine", and by the 1700s alcohol alone meant the spirit. The al- is the Arabic article, as in algebra and alkali, which are otherwise unrelated.',
    family: ['kohl', 'alcopop'],
    notes: { kohl: 'the eyeliner, the original Arabic word' },
    friends: [['alchemy', 'Arabic al-kīmiyā, a different al- word'], ['algebra', 'Arabic al-jabr, reunion of broken parts'], ['alkali', 'Arabic al-qalī, the ashes']] },
  { word: 'nicotine', level: 2, cat: 'pharmacopoeia', origin: 'Named for the French ambassador who sent tobacco seeds from Lisbon to Paris in 1560. He was called Nicot, and the plant was called after him first.',
    story: 'Jean Nicot, French ambassador in Lisbon, sent tobacco to Catherine de\' Medici in 1560 as a cure for headaches. Botanists named the plant Nicotiana after him, and French chemists who isolated its alkaloid in 1828 called it nicotine. Nicot\'s own name is a pet form of Nicolas, from Greek Nikolaos, "victory of the people", which puts Nike, the goddess of victory, at the bottom of the cigarette.',
    family: ['Nicotiana', 'Nicolas', 'Nicholas', 'Nike', 'Nicole'],
    notes: { Nike: 'Greek for victory, the first half of Nicolas', Nicholas: 'Greek Nikolaos, "people\'s victory"' },
    friends: [['nick', 'origin unknown'], ['nickel', 'German Kupfernickel, "copper demon"'], ['tobacco', 'Spanish tabaco, from Taino or Arabic']] },
  { word: 'caffeine', level: 2, cat: 'pharmacopoeia', origin: 'German, 1819, from the word for the drink it was found in. That drink\'s name is Arabic, and before that possibly an Ethiopian region.',
    story: 'Friedlieb Runge isolated the alkaloid from coffee beans in 1819 and named it Kaffein; French caféine and English caffeine followed by 1830. Coffee is Arabic qahwa, a word that may earlier have meant wine, passed through Turkish kahve and Italian caffè into English around 1600. The theory that qahwa comes from Kaffa, the Ethiopian region, is unproven.',
    family: ['coffee', 'café', 'cafeteria', 'decaf', 'caffeinated', 'decaffeinated'],
    notes: { cafeteria: 'American Spanish, "coffee shop"' },
    friends: [['calf', 'Old English cealf'], ['gaffe', 'French, a blunder'], ['kefir', 'Caucasian, unrelated']] },
  { word: 'psychedelic', level: 2, cat: 'pharmacopoeia', origin: 'Coined in 1956 by a doctor writing to Aldous Huxley: Greek for "mind-showing". The mind half is the word for breath and soul.',
    story: 'Humphry Osmond proposed psychedelic to Aldous Huxley in a 1956 letter, from Greek psychē, "mind, soul", and dēloun, "to make visible". Psychē was originally breath, from psychein, "to blow", and became the soul that leaves with the last breath. The same word is in psychology, psychiatry and the psychopath. Dēlos, "visible", is rare elsewhere in English.',
    family: ['psyche', 'psychology', 'psychiatry', 'psychic', 'psychopath', 'psychosis', 'psychosomatic', 'psychotherapy', 'psychoanalysis', 'psychiatrist'],
    notes: { psyche: 'Greek for breath, then soul, then mind' },
    friends: [['physics', 'Greek physis, nature'], ['cycle', 'Greek kyklos, wheel'], ['psalm', 'Greek psallein, to pluck']] },
  { word: 'morphine', level: 2, cat: 'pharmacopoeia', origin: 'Named in 1817 for the Greek god of dreams, whose own name means "shaper". A word for form and shape is under it.',
    story: 'Friedrich Sertürner, who isolated the alkaloid from opium in 1804, named it morphium in 1817 after Morpheus, Ovid\'s god of dreams. Morpheus is Greek morphē, "form, shape": the god who shapes dreams. The same word gives morphology, metamorphosis (a change of shape), amorphous (shapeless) and, in linguistics, the morpheme.',
    family: ['Morpheus', 'morphology', 'metamorphosis', 'amorphous', 'morpheme', 'morph', 'anthropomorphic', 'polymorphic'],
    notes: { Morpheus: 'the god of dreams, "the shaper"', amorphous: 'Greek a- + morphē, without form' },
    friends: [['moron', 'Greek moros, foolish'], ['morbid', 'Latin morbus, disease'], ['mortal', 'Latin mors, death']] },
  { word: 'heroin', level: 2, cat: 'pharmacopoeia', origin: 'A trade name from 1898, said to come from the German for what Achilles was, for how it made the test subjects feel. The word for that kind of man is Greek.',
    story: 'Bayer trademarked Heroin in 1898 as a cough suppressant; the name is usually explained from German heroisch, "heroic", after the euphoria reported by workers who tried it. Greek hērōs was a demigod, then any great man; Latin heros, French héros, and English hero by the 1300s. The heroine is the feminine. The Greek word\'s own origin is uncertain; some link it to Hera.',
    family: ['hero', 'heroine', 'heroic', 'heroism', 'antihero', 'superhero'],
    notes: {},
    friends: [['heron', 'Old French hairon, Germanic'], ['herald', 'Frankish, army-ruler'], ['herring', 'Old English hæring']] },
  { word: 'cocaine', level: 2, cat: 'pharmacopoeia', origin: 'Coined in 1860 from the Andean shrub whose leaf it comes from; that name is Quechua. The cacao tree is a different plant with a similar-looking name.',
    story: 'Albert Niemann isolated the alkaloid in 1860 and named it from coca plus the chemists\' suffix -ine. Coca is Spanish, from Quechua kuka, the leaf Andean people have chewed for millennia. Coca-Cola, 1886, took its first half from the leaf and its second from the kola nut. Cacao and cocoa, from Nahuatl cacahuatl, are unrelated despite the spelling.',
    family: ['coca', 'Coca-Cola', 'coke', 'kuka'],
    notes: { coke: 'the slang, from cocaine, 1903; the fuel coke is unrelated' },
    friends: [['cocoa', 'Nahuatl cacahuatl, a different plant'], ['coconut', 'Portuguese coco, a grinning face'], ['cock', 'Old English cocc']] },
  { word: 'tequila', level: 1, cat: 'pharmacopoeia', origin: 'The town in Jalisco where it is made. The town\'s name is Nahuatl and probably refers to the place where a certain kind of work was done.',
    story: 'Tequila is named for the town of Tequila in Jalisco, Mexico, around which the blue agave grows; the drink was called vino de Tequila by the 1600s and plain tequila in English from 1849. The town\'s Nahuatl name, Tequillan, is usually explained as "place of tribute" or "place of work", from tequitl, "work, tribute". Mezcal, the older name for agave spirit, is Nahuatl mexcalli, "oven-cooked agave".',
    family: ['mezcal', 'mescal', 'agave', 'Tequillan'],
    notes: { mezcal: 'family by kinship of drink, not of word: Nahuatl mexcalli, cooked agave', agave: 'Greek agauē, noble, a botanist\'s name for the plant' },
    friends: [['tequila sunrise', 'counts'], ['tortilla', 'Spanish torta, a cake'], ['tea', 'Chinese te']] },
  { word: 'absinthe', level: 3, cat: 'pharmacopoeia', origin: 'French, from the Latin and Greek name of the bitter herb it is flavoured with. The Greek word is probably a borrowing from further east.',
    story: 'Greek apsinthion was wormwood, Artemisia absinthium, the bitter herb; Latin absinthium, Old French absinthe. English had absinthium for the plant by the 1400s and absinthe for the green spirit, invented in Switzerland around 1790, by 1842. The Greek word is not Indo-European; it was probably borrowed from a Near Eastern language. Wormwood, the English name, is an alteration of Old English wermod, which is also vermouth by way of German.',
    family: ['absinthium', 'wormwood', 'vermouth', 'Wermut'],
    notes: { wormwood: 'family by kinship of plant: Old English wermod, the same herb', vermouth: 'German Wermut, wormwood, the herb that flavours it' },
    friends: [['absent', 'Latin abesse, to be away'], ['absolute', 'Latin absolvere, to loosen'], ['sin', 'Old English synn']] },

  // ---------------- The mind ----------------
  { word: 'genius', level: 3, cat: 'mind', origin: 'Latin genius, the guardian spirit born with each person. The root means "to beget, to be born", and it is one of the biggest families in the language.',
    story: 'Latin genius was the spirit that attended a person from birth, from gignere, "to beget". By the 1600s English used it for a person\'s natural bent, and by the 1700s for exceptional inborn ability. The root gen-, "to give birth", is everywhere: gene, generate, generous (well-born), gentle (of good family), genuine, nation (nasci, to be born), nature, pregnant, benign (well-born), and by the Germanic road kin, kind and king (the son of the kin).',
    family: ['gene', 'genetic', 'generate', 'generation', 'general', 'generous', 'genre', 'gender', 'genie', 'genital', 'engine', 'ingenious', 'indigenous', 'congenital', 'progeny', 'gentle', 'gentleman', 'genocide', 'oxygen', 'hydrogen', 'kin', 'kind', 'king', 'nation', 'nature', 'native', 'pregnant', 'benign', 'malign', 'germ', 'germane', 'genesis', 'genealogy', 'gentry', 'naive', 'nascent', 'renaissance', 'cognate'],
    notes: { engine: 'Latin ingenium, "inborn talent", then a clever device', generous: 'Latin generosus, of noble birth', gentle: 'Latin gentilis, of the same clan', king: 'Old English cyning, "son of the kin"', kind: 'Old English gecynd, nature, inborn character', nation: 'Latin natio, a birth, a people', pregnant: 'Latin praegnans, "before birth"', benign: 'Latin benignus, "well-born", then kindly', germ: 'Latin germen, a sprout, from the same begetting root', naive: 'French naïf, "as born", natural', oxygen: 'the -gen half: "producer"', genie: 'French génie from genius, later blended with Arabic jinn' },
    friends: [['gin', 'juniper, via Dutch'], ['genuflect', 'Latin genu, knee'], ['gentian', 'King Gentius of Illyria']] },
  { word: 'spirit', level: 1, cat: 'mind', origin: 'Latin spirare, "to breathe". A spirit was a breath before it was a ghost or a drink.',
    story: 'Latin spiritus, "breath, breathing", from spirare, "to breathe", was used in the Vulgate for the Hebrew ruach and Greek pneuma, the breath of God, and so came to mean the soul. English took spirit from Anglo-French in the 1200s. The distilled sense, from the 1500s, is the alchemists\' "spirit" or vapour of a substance. Inspire is to breathe in, expire to breathe out, conspire to breathe together, perspire to breathe through the skin.',
    family: ['inspire', 'expire', 'respire', 'respiration', 'conspire', 'conspiracy', 'perspire', 'aspire', 'transpire', 'spiritual', 'esprit', 'sprite', 'spiracle', 'dispirited', 'inspiration', 'respirator'],
    notes: { sprite: 'Old French esprit, spirit, a small one', spiracle: 'a breathing hole in an insect', esprit: 'French for spirit, as in esprit de corps' },
    friends: [['spiral', 'Greek speira, coil'], ['spire', 'Old English, a stalk'], ['spit', 'Old English, no relation']] },
  { word: 'lunatic', level: 2, cat: 'mind', origin: 'Latin luna, the moon. Madness was thought to come and go with its phases. The root means "brightness", and it shines through a good deal of Latin.',
    story: 'Latin luna, "moon", gave lunaticus, "moonstruck", because madness was believed to wax and wane with the moon; Old French lunatique reached English around 1300. Luna comes from a root meaning "light, brightness" that also gives Latin lux and lumen: lucid, illuminate, luminous, illustrate (to light up), lustre, and Lucifer, "the light-bearer", the morning star. English light is the same root by the Germanic road.',
    family: ['lunar', 'lunation', 'sublunary', 'lucid', 'lucent', 'translucent', 'elucidate', 'illuminate', 'luminous', 'luminary', 'luster', 'lustre', 'illustrate', 'lux', 'light', 'Lucifer', 'lucifer', 'lunacy', 'Lucy', 'lucent'],
    notes: { lucid: 'Latin lucidus, bright, from lux', illustrate: 'Latin illustrare, to light up', Lucifer: 'Latin, "light-bearer", the morning star', light: 'Old English leoht, the same root', lucifer: 'a friction match, 1830s', Lucy: 'Latin Lucia, "light"' },
    friends: [['lunch', 'origin unknown'], ['lung', 'Old English, "light" in weight, a different light'], ['lunge', 'French allonger']] },
  { word: 'terror', level: 1, cat: 'mind', origin: 'Latin terrere, "to frighten", from a root meaning "to shake, to quiver". The shaking is still in several English words.',
    story: 'Latin terrere, "to fill with fear", from an Indo-European root tres-, "to tremble", gave terror, and Old French terreur reached English in the late 1300s. Terrible, terrific (which meant frightening until the 1800s) and deter (to frighten off) are the same verb. The trembling root also gives Latin tremere, which is tremble, tremor and tremendous, "to be trembled at".',
    family: ['terrible', 'terrific', 'terrify', 'deter', 'deterrent', 'tremble', 'tremor', 'tremendous', 'tremulous'],
    notes: { deter: 'Latin deterrere, to frighten away', terrific: 'causing terror, until the 1800s turned it round', tremble: 'Latin tremulus, from the same trembling root', tremendous: 'Latin tremendus, "to be trembled at"' },
    friends: [['terrain', 'Latin terra, earth'], ['territory', 'terra again'], ['terrier', 'terra, an earth dog']] },
  { word: 'sanity', level: 1, cat: 'mind', origin: 'Latin sanus, "healthy, sound". It was bodily health first; the mind came later. Its family is mostly about keeping things clean.',
    story: 'Latin sanus, "healthy", gave sanitas, "health", which is sanity, in English by the 1400s in the bodily sense; "soundness of mind" is from the 1600s. Sane arrived in the 1700s already meaning of sound mind. Sanitary and sanitation, coined in the 1800s, go back to the same health, and a sanatorium is a place for getting healthy. The origin of sanus before Latin is unknown.',
    family: ['sane', 'insane', 'sanitary', 'sanitation', 'sanitize', 'sanatorium', 'sanitarium', 'insanity', 'sanitizer'],
    notes: { sanatorium: 'Latin sanare, to heal' },
    friends: [['saint', 'Latin sanctus, holy'], ['sanction', 'sanctus again'], ['sand', 'Old English']] },
  { word: 'psyche', level: 1, cat: 'mind', origin: 'Greek for breath, then for the soul that leaves with the last one, then for the mind. From a verb meaning "to blow".',
    story: 'Greek psychē meant breath, from psychein, "to blow, breathe", and then the soul or spirit, the thing that departs with the last breath; Homer\'s dead are psychai. Later philosophers made it the mind. English borrowed it directly in the 1600s. Psychology, "the study of the soul", was coined in Latin in the 1500s, psychiatry ("soul-healing") in 1808, the psychopath in 1885.',
    family: ['psychology', 'psychiatry', 'psychedelic', 'psychopath', 'psychosis', 'psychosomatic', 'psychotherapy', 'psychoanalysis', 'psychiatrist'],
    notes: { psychedelic: 'Greek psychē + dēloun, "mind-showing", 1956' },
    friends: [['physics', 'Greek physis, nature'], ['cycle', 'Greek kyklos, wheel'], ['psalm', 'Greek psallein, to pluck']] },
  { word: 'hypnosis', level: 1, cat: 'mind', origin: 'Greek hypnos, "sleep", and the god of it. Coined in the 1870s from an earlier "hypnotism". The Latin word for sleep is the same root, and it gives the English words for not sleeping.',
    story: 'Greek hypnos, "sleep", was also the god Hypnos, brother of Death. The Scottish surgeon James Braid coined hypnotism in 1841 for the trance he induced, and hypnosis followed in the 1870s. Hypnos and Latin somnus are the same Indo-European word, swep-, which also gives Latin sopor and, by the Germanic road, an old English word swefn, "dream". Insomnia is "no sleep", a somnambulist a sleep-walker.',
    family: ['hypnotic', 'hypnotize', 'hypnotherapy', 'somnolent', 'insomnia', 'somnambulist', 'soporific', 'hypnotist', 'insomniac'],
    notes: { insomnia: 'Latin in- + somnus, sleep, the same root as hypnos', somnambulist: 'Latin somnus + ambulare, sleep-walker', soporific: 'Latin sopor, deep sleep, the same root' },
    friends: [['hypo', 'Greek hypo, under: a different word'], ['hymn', 'Greek hymnos'], ['sleep', 'Old English slæpan, unrelated']] },
  { word: 'euphoria', level: 2, cat: 'mind', origin: 'Greek eu, "well", plus a verb meaning "to carry": carrying things easily. The carrying verb is one of the great roots, and English has it too.',
    story: 'Greek euphoros, "bearing well", gave euphoria, which Greek doctors used for a patient\'s sense of well-being; English took it as a medical term in the 1680s and as plain elation in the 1800s. Pherein, "to carry", is the Indo-European root bher-, which is Latin ferre (transfer, refer, prefer, suffer, fertile) and English bear, birth and burden. A metaphor carries a meaning across; phosphorus is the light-bearer.',
    family: ['metaphor', 'semaphore', 'phosphorus', 'periphery', 'amphora', 'anaphora', 'fertile', 'ferry', 'bear', 'birth', 'burden', 'transfer', 'refer', 'prefer', 'differ', 'offer', 'suffer', 'confer', 'infer', 'circumference', 'aquifer', 'conifer', 'Lucifer', 'Christopher', 'euphemism', 'eulogy', 'euthanasia', 'evangelist', 'euphoric'],
    notes: { metaphor: 'Greek metapherein, to carry across', amphora: 'Greek, "carried on both sides", by two handles', periphery: 'Greek, "carried around"', ferry: 'Old English ferian, to carry, the same root', birth: 'Old Norse byrth, a bearing', Christopher: '"Christ-bearer"', Lucifer: '"light-bearer"', euphemism: 'shares the eu-, "well", half only', euthanasia: 'the eu- half only' },
    friends: [['euro', 'Europa'], ['fury', 'Latin furere, to rage'], ['fern', 'Old English fearn']] },
  { word: 'anxiety', level: 2, cat: 'mind', origin: 'Latin angere, "to choke, to squeeze", from a root meaning "narrow, tight". Several kinds of pain and one kind of rage share it.',
    story: 'Latin angere, "to choke, throttle, distress", from the root angh-, "tight, painful", gave anxius, "troubled", and anxietas; English anxiety is from the 1520s. Anguish is Latin angustia, "narrowness", by way of French. Angina is the choking chest pain. Anger is Old Norse angr, "grief, trouble", the same tightness by the Germanic road, and angst is the German cousin. Quinsy, the old name for an abscess of the throat, is Greek kynanchē, "dog-choking".',
    family: ['anxious', 'anger', 'angina', 'anguish', 'angst', 'hangnail', 'quinsy', 'angry'],
    notes: { anger: 'Old Norse angr, distress, the same root', hangnail: 'Old English angnægl, a painful nail; the "hang" is folk spelling', quinsy: 'Greek kynanchē, "dog-strangling", a throat abscess' },
    friends: [['angel', 'Greek angelos, messenger'], ['angle', 'Latin angulus, corner'], ['ankle', 'Old English ancleow']] },
  { word: 'trauma', level: 2, cat: 'mind', origin: 'Greek for "a wound". English used it only for bodily injury until Freud\'s generation moved it into the mind. The root meant "to rub, to wear through".',
    story: 'Greek trauma, "wound, hurt", from a root meaning "to rub, to bore through", was borrowed into English medical Latin in the 1690s for a physical injury; the psychological sense dates from the 1890s. The rubbing root, tere-, gives Latin terere, "to rub, wear down": trite (worn), attrition, contrite (worn down with guilt), detriment, tribulation (from tribulum, a threshing sledge). By the Germanic road it gives throw (originally to twist) and thread.',
    family: ['traumatic', 'traumatize', 'trite', 'tribulation', 'attrition', 'contrite', 'detriment', 'throw', 'thread', 'turn', 'tribology', 'traumatised'],
    notes: { trite: 'Latin tritus, worn by use', tribulation: 'Latin tribulum, a threshing sledge that rubs the grain out', contrite: 'Latin contritus, ground down', throw: 'Old English thrawan, to twist, turn', turn: 'Greek tornos, a lathe, the same rubbing-turning root', tribology: 'the science of friction' },
    friends: [['tram', 'Low German traam, beam'], ['drama', 'Greek dran, to do'], ['trauma centre', 'counts']] },
  { word: 'delirium', level: 2, cat: 'mind', origin: 'Latin delirare, "to go off the furrow", from the word for the ridge a plough leaves. A mind that has wandered out of the row.',
    story: 'Latin lira was the ridge of earth between furrows; delirare, "to leave the furrow", was farmers\' talk for going astray, and delirium was the noun by Cicero\'s time. English took it in the 1590s. Delirium tremens, "trembling delirium", was named in 1813. Lira has no other English family; the tremens is Latin tremere, which is family to tremble and terror.',
    family: ['delirious', 'delirium tremens', 'deliriously'],
    notes: {},
    friends: [['deliver', 'Latin liber, free'], ['delight', 'Latin delectare'], ['lyre', 'Greek lyra']] },
  { word: 'paranoia', level: 2, cat: 'mind', origin: 'Greek for "beside the mind", the way you say someone is beside themselves. The mind half is a Greek word English uses for common sense.',
    story: 'Greek paranoia, "madness", is para, "beside, beyond", plus nous, "mind": a mind gone off to the side. Hippocrates used it for any derangement. Modern psychiatry revived it in Latin form in 1811 and narrowed it to delusions of persecution. Nous gives few other English words; the para- gives many: paradox, parallel, parasite (one who eats beside you), parody, paragraph.',
    family: ['paranoid', 'nous', 'paradox', 'parallel', 'parasite', 'parody', 'paragraph', 'paramedic', 'parable', 'paralysis'],
    notes: { nous: 'Greek for mind, the second half; in English slang, common sense', parasite: 'Greek parasitos, "one who eats beside", a hanger-on at dinner', parable: 'Greek parabolē, a placing beside, a comparison' },
    friends: [['pair', 'Latin par, equal'], ['parrot', 'French perrot, a pet form of Pierre'], ['pariah', 'Tamil paraiyar, drummers']] },
  { word: 'melancholy', level: 2, cat: 'mind', origin: 'Greek for "black bile", the humour that was supposed to cause it. The black half and the bile half both have relatives in English.',
    story: 'Greek melankholia is melas, "black", plus kholē, "bile": in humoral medicine an excess of black bile made you gloomy. Old French melancolie reached English around 1300. Melas gives melanin, melanoma and Melanesia, "the black islands". Kholē is choler, the yellow bile of the hot-tempered, hence choleric, and cholera, and the gall it corresponds to in Germanic is the same root.',
    family: ['melanin', 'melanoma', 'Melanesia', 'choler', 'choleric', 'cholera', 'cholesterol', 'gall', 'melatonin'],
    notes: { cholesterol: 'Greek kholē + stereos, "bile-solid", first found in gallstones', gall: 'Old English gealla, bile, the same root as kholē', melatonin: 'named from melanin, which it affects' },
    friends: [['melon', 'Greek mēlon, apple'], ['melody', 'Greek melos, a song'], ['collar', 'Latin collum, neck']] },
  { word: 'hysteria', level: 2, cat: 'mind', origin: 'Greek for the womb. Ancient doctors blamed the organ, which they believed could wander, for the condition; the name outlived the theory.',
    story: 'Greek hystera, "womb", gave hysterikos, "of the womb", because Greek and later physicians believed the condition was caused by disturbances of the uterus, which Plato thought wandered the body. English had hysteric in the 1600s and coined hysteria in 1801. Hysterectomy is the removal of the same organ. The Greek word may be related to Latin uterus, though the link is disputed.',
    family: ['hysterical', 'hysterectomy', 'hysterics', 'hysteric'],
    notes: { hysterectomy: 'the surgical removal of the hystera' },
    friends: [['history', 'Greek histor, one who knows'], ['hysteresis', 'Greek hysteros, later: a different word'], ['uterus', 'Latin, possibly a cousin, not proven']] },
  { word: 'phobia', level: 1, cat: 'mind', origin: 'Greek for fear and panic flight. A god of the same name rode with Ares. The word was mostly a suffix until doctors let it stand alone in 1786.',
    story: 'Greek phobos meant panic flight and then fear; Phobos was the personification who accompanied Ares into battle, and one of the moons of Mars is named for him. Latin -phobia was used in compounds like hydrophobia, the dread of water in rabies, and English writers detached phobia as a word on its own in 1786. Claustrophobia (Latin claustrum, an enclosed place) was coined in 1879.',
    family: ['phobic', 'hydrophobia', 'claustrophobia', 'agoraphobia', 'arachnophobia', 'xenophobia', 'homophobia', 'Phobos'],
    notes: { Phobos: 'the god, and the larger moon of Mars', hydrophobia: 'Greek, "water-fear", the old name for rabies' },
    friends: [['phone', 'Greek phōnē, voice'], ['foe', 'Old English fah, hostile'], ['fob', 'German dialect, a pocket']] },
  { word: 'idiot', level: 2, cat: 'mind', origin: 'Greek idiōtēs, a private person, one who held no public office. The Athenians thought poorly of that, and the word went downhill from there.',
    story: 'Greek idios, "one\'s own, private", gave idiōtēs, a private citizen as opposed to one who takes part in public life, and then a layman, an ignorant person. Latin idiota was an uneducated man, Old French idiote a simpleton, and English idiot, around 1300, a person of profound intellectual disability, a legal category until the 1900s. Idios also gives idiom (one\'s own way of speaking) and idiosyncrasy (one\'s own mixture of temperament).',
    family: ['idiom', 'idiosyncrasy', 'idiocy', 'idiomatic', 'idiopathic'],
    notes: { idiom: 'Greek idiōma, a peculiarity of one\'s own', idiopathic: 'a disease "of its own", with no known cause' },
    friends: [['idea', 'Greek idein, to see'], ['idol', 'idein again'], ['idle', 'Old English idel, empty']] },
  { word: 'nostalgia', level: 2, cat: 'mind', origin: 'Coined in 1688 by a Swiss medical student, from Greek for "homecoming" and "pain", to name the sickness of Swiss mercenaries far from the Alps.',
    story: 'Johannes Hofer put nostalgia together in his 1688 dissertation from Greek nostos, "return home", and algos, "pain", to translate German Heimweh, the homesickness that was killing Swiss soldiers abroad. It was a medical diagnosis for two centuries before it softened into wistfulness for the past in the 1900s. Nostos is Odysseus\'s word for his homecoming. Algos is in neuralgia, analgesic ("without pain") and myalgia.',
    family: ['nostalgic', 'neuralgia', 'analgesic', 'myalgia', 'fibromyalgia', 'analgesia'],
    notes: { analgesic: 'Greek an- + algos, "no pain"', neuralgia: 'nerve pain' },
    friends: [['nostril', 'Old English nosu + thyrl, nose-hole'], ['nostrum', 'Latin, "ours", a quack\'s own remedy'], ['Nostradamus', 'a Latinised surname']] },
  { word: 'oblivion', level: 2, cat: 'mind', origin: 'Latin oblivisci, "to forget". The likeliest root is a word for "smooth": to forget is to have the mark wiped level.',
    story: 'Latin oblivio, "forgetfulness", from oblivisci, "to forget", reached English through Old French in the late 1300s; "the state of being forgotten" came first and "unconsciousness" in the 1800s. The Latin verb is probably from ob- plus levis, "smooth", the idea being a wax tablet wiped level. The same levis, "smooth, light", gives levity, elevate, lever, relieve and alleviate, but the link to forgetting is only probable, so this family stays small.',
    family: ['oblivious', 'obliviousness', 'levity', 'elevate', 'lever', 'relieve', 'alleviate', 'levitate'],
    notes: { levity: 'Latin levis, light: probably the smooth-wiped tablet that oblivion comes from', lever: 'Latin levare, to lift, the same levis' },
    friends: [['oblige', 'Latin ligare, to bind'], ['oblong', 'Latin longus'], ['olive', 'Greek elaia']] },
  { word: 'enthusiasm', level: 2, cat: 'mind', origin: 'Greek for "having a god inside you". It meant possession, and for a long time the English word was an insult for religious zealots.',
    story: 'Greek enthousiasmos, from entheos, "god-possessed" (en, "in", plus theos, "god"), described the frenzy of a prophet or a poet inspired by a god. English took it in the 1600s and used it mostly with contempt for religious fanatics until the late 1700s, when it became simply eager interest. Theos is in theology, atheist, pantheon, apotheosis and, through Latin, the name Timothy, "honouring God".',
    family: ['enthusiast', 'enthusiastic', 'theology', 'atheist', 'pantheon', 'apotheosis', 'polytheism', 'monotheism', 'Timothy', 'Theodore', 'Dorothy'],
    notes: { pantheon: 'Greek, "all the gods"', apotheosis: 'being made into a god', Dorothy: 'Greek Dorothea, "gift of God", the same halves as Theodore reversed' },
    friends: [['enthrone', 'Greek thronos, a seat'], ['theatre', 'Greek theasthai, to watch'], ['theme', 'Greek tithenai, to put']] },
];
